In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [7]:
db_uri = "mysql+pymysql://statsuser:statspass@localhost:3306/statsdb"
engine = create_engine(db_uri)

guery = """
SELECT *
FROM statistic
WHERE type = 'movieFavoriteAdded';
"""

In [8]:
df = pd.read_sql(guery, engine)

In [10]:
df.drop_duplicates()
df

,id,cusRef,devRef,devType,devModel,timeZone,cusGrRefs,ref,type,name,time,duration,extra,deliveredTS,insertedTS
0,50582438481,993150002904659,9931500029046591,MOTOROLA_4,VIP1113,UTC+01:00,"[""1006"",""C1"",""0""]",32da254a369d2065bc179786b188b9e9,movieFavoriteAdded,Plavi mesec,1776723973199,None,"{""movieId"":""132220"",""shopRef"":""3""}",1776724113918,2026-04-21 00:28:43
1,50583326850,549013002495481,5490130024954812,MOTOROLA_4,VIP1113,UTC+01:00,"[""100128"",""100131"",""R1"",""1006"",""C1"",""0"",""V0""]",8eeb2c0dab0e3642d778851acb2144db,movieFavoriteAdded,Devojačko veče,1776729779056,None,"{""movieId"":""129235"",""shopRef"":""1""}",1776729844330,2026-04-21 02:04:10
2,50583326851,549013002495481,5490130024954812,MOTOROLA_4,VIP1113,UTC+01:00,"[""100128"",""100131"",""R1"",""1006"",""C1"",""0"",""V0""]",8eeb2c0dab0e3642d778851acb2144db,movieFavoriteAdded,Devojačko veče,1776729781055,None,"{""movieId"":""129235"",""shopRef"":""1""}",1776729844330,2026-04-21 02:04:10
3,50587096474,517730002465985,5177300024659851,MOTOROLA_4,VIP1113,UTC+02:00,"[""100128"",""1006"",""C1"",""0"",""V0"",""R1""]",dae94285eed2e1b74e4bd311c6ad4422,movieFavoriteAdded,Predsednikov čovek 2,1776760463913,None,"{""movieId"":""87334"",""shopRef"":""18""}",1776760495826,2026-04-21 10:35:01
4,50587096476,517730002465985,5177300024659851,MOTOROLA_4,VIP1113,UTC+02:00,"[""100128"",""1006"",""C1"",""0"",""V0"",""R1""]",dae94285eed2e1b74e4bd311c6ad4422,movieFavoriteAdded,Predsednikov čovek 2,1776760466202,None,"{""movieId"":""87334"",""shopRef"":""18""}",1776760495826,2026-04-21 10:35:01
5,50589468657,155733000942944,1557330009429441,MOTOROLA_4,VIP1113,UTC+02:00,"[""100128"",""1006"",""A0"",""C1"",""0"",""A1"",""A2"",""V0"",...",1e7378f53cc93057cb26624871a18fd4,movieFavoriteAdded,Ričard roda 2,1776776729802,None,"{""movieId"":""127282"",""shopRef"":""18""}",1776776918082,2026-04-21 15:08:41
6,50590729499,528681001793596,5286810017935961,MOTOROLA_4,VIP1113,UTC+02:00,"[""1006"",""C1"",""0"",""V0"",""R1""]",075c8e99c8895ec3c4f004099f24ccfd,movieFavoriteAdded,"Porodica Soprano V, ep. 1",1776784530676,None,"{""movieId"":""60980"",""shopRef"":""3""}",1776784587423,2026-04-21 17:16:32
7,50590729501,528681001793596,5286810017935961,MOTOROLA_4,VIP1113,UTC+02:00,"[""1006"",""C1"",""0"",""V0"",""R1""]",d78753fa82a82149f4cb1d2d3573e8cb,movieFavoriteAdded,"Porodica Soprano V, ep. 3",1776784548097,None,"{""movieId"":""60969"",""shopRef"":""3""}",1776784587423,2026-04-21 17:16:32
8,50590729502,528681001793596,5286810017935961,MOTOROLA_4,VIP1113,UTC+02:00,"[""1006"",""C1"",""0"",""V0"",""R1""]",699a88d059a75cbb4df00eca1a023a3d,movieFavoriteAdded,"Porodica Soprano V, ep. 2",1776784540215,None,"{""movieId"":""60972"",""shopRef"":""3""}",1776784587423,2026-04-21 17:16:32
9,50590729503,528681001793596,5286810017935961,MOTOROLA_4,VIP1113,UTC+02:00,"[""1006"",""C1"",""0"",""V0"",""R1""]",84560ed5764076a3a0b0005ed558517d,movieFavoriteAdded,"Porodica Soprano V, ep. 4",1776784556832,None,"{""movieId"":""60968"",""shopRef"":""3""}",1776784587423,2026-04-21 17:16:32
10,50590729504,528681001793596,5286810017935961,MOTOROLA_4,VIP1113,UTC+02:00,"[""1006"",""C1"",""0"",""V0"",""R1""]",2c68e9a1b3706d27f77d2df0f5b60661,movieFavoriteAdded,"Porodica Soprano V, ep. 5",1776784561734,None,"{""movieId"":""60970"",""shopRef"":""3""}",1776784587423,2026-04-21 17:16:32
11,50590729505,528681001793596,5286810017935961,MOTOROLA_4,VIP1113,UTC+02:00,"[""1006"",""C1"",""0"",""V0"",""R1""]",fc0e041754f830807aab0cf9a411ad1d,movieFavoriteAdded,"Porodica Soprano V, ep. 7",1776784572033,None,"{""movieId"":""60989"",""shopRef"":""3""}",1776784587423,2026-04-21 17:16:32
12,50590729508,528681001793596,5286810017935961,MOTOROLA_4,VIP1113,UTC+02:00,"[""1006"",""C1"",""0"",""V0"",""R1""]",62e4de6a46a92908de124c0f5627b18a,movieFavoriteAdded,"Porodica Soprano V, ep. 10",1776784587389,None,"{""movieId"":""60982"",""shopRef"":""3""}",1776784587423,2026-04-21 17:16:32
13,50590729509,528681001793596,5286810017935961,MOTOROLA_4,VIP1113,UTC+02:00,"[""1006"",""C1"",""0"",""V0"",""R1""]",e5d2f95524975966dfd6bf72ca826660,movieFavoriteAdded,"Porodica Soprano V, ep. 8",1776784578215,None,"{""movieId"":""60986"",""shopRef"":""3""}",1776784587423,2026-04-21 17:16:32
14,50590729510,528681001793596,5286810017935961,MOTOROLA_4,VIP1113,UTC+02:00,"[""1006"",""C1"",""0"",""V0"",""R1""]",0144a5843ecc6a3ecc49bdc5b2a2a276,movieFavoriteAdded,"Porodica Soprano V, ep. 6",1776784566600,None,"{""movieId"":""60973"",""shopRef"":""3""}",1776784587423,2026-04-21 17:16:32
15,50590729511,528681001793596,5286810017935961,MOTOROLA_4,VIP1113,UTC+02:00,"[""1006"",""C1"",""0"",""V0"",""R1""]",e7f3d1afd6fe70eb820d6334ba2c587d,movieFavoriteAdded,"Porodica Soprano V, ep. 9",1776784582729,None,"{""movieId"":""60985"",""shopRef"":""3""}",1776784587423,2026-04-21 17:16:32
16,50593178341,969059002496486,9690590024964862,MOTOROLA_4,VIP1113,UTC+02:00,"[""1006"",""C1"",""0"",""V0"",""R1""]",8f137200a28befd77a0f2bfa57f715a6,movieFavoriteAdded,Bekstvo iz Danemore S01E01,1776796506181,None,"{""movieId"":""102431"",""shopRef"":""18""}",1776796696991,2026-04-21 20:38:22
17,50593178342,969059002496486,9690590024964862,MOTOROLA_4,VIP1113,UTC+02:00,"[""1006"",""C1"",""0"",""V0"",""R1""]",2aecdd9ab1c9b1642db391195880830a,movieFavoriteAdded,Breht S01E01,1776796670848,None,"{""movieId"":""110806"",""shopRef"":""18""}",1776796696991,2026-04-21 20:38:22
18,50593245007,969059002496486,9690590024964862,MOTOROLA_4,VIP1113,UTC+02:00,"[""1006"",""C1"",""0"",""V0"",""R1""]",bd396d1898d08225aafb1883b5d10549,movieFavoriteAdded,Hari Vajld S0201,1776796901078,None,"{""movieId"":""130314"",""shopRef"":""18""}",1776796997195,2026-04-21 20:43:25
19,50593245008,969059002496486,9690590024964862,MOTOROLA_4,VIP1113,UTC+02:00,"[""1006"",""C1"",""0"",""V0"",""R1""]",169cc0311f47accd84024ef90729c804,movieFavoriteAdded,Istina o slučaju Harija Kebera S,1776796971802,None,"{""movieId"":""99808"",""shopRef"":""18""}",1776796997195,2026-04-21 20:43:25
20,50593313885,969059002496486,9690590024964862,MOTOROLA_4,VIP1113,UTC+02:00,"[""1006"",""C1"",""0"",""V0"",""R1""]",f78a8ade10290e201b9ff8c636b9c1da,movieFavoriteAdded,Izjednačavanje S01E01,1776797026708,None,"{""movieId"":""103729"",""shopRef"":""18""}",1776797297461,2026-04-21 20:48:17
21,50593313886,969059002496486,9690590024964862,MOTOROLA_4,VIP1113,UTC+02:00,"[""1006"",""C1"",""0"",""V0"",""R1""]",53fa30e6511a12142d3c85aa0fd93fc1,movieFavoriteAdded,Klaris S01E01,1776797156912,None,"{""movieId"":""101008"",""shopRef"":""18""}",1776797297461,2026-04-21 20:48:17
22,50593313888,969059002496486,9690590024964862,MOTOROLA_4,VIP1113,UTC+02:00,"[""1006"",""C1"",""0"",""V0"",""R1""]",d2c2bb527544a9f4283515d2bc25cbd2,movieFavoriteAdded,Lovci na ukuse S01E01,1776797266327,None,"{""movieId"":""120954"",""shopRef"":""18""}",1776797297461,2026-04-21 20:48:17
23,50593454185,969059002496486,9690590024964862,MOTOROLA_4,VIP1113,UTC+02:00,"[""1006"",""C1"",""0"",""V0"",""R1""]",13b0966e50601ca90b4b863de3ee3e96,movieFavoriteAdded,Počni već jbtnom S01E01,1776797668050,None,"{""movieId"":""119127"",""shopRef"":""18""}",1776797898879,2026-04-21 20:58:24
24,50593454186,969059002496486,9690590024964862,MOTOROLA_4,VIP1113,UTC+02:00,"[""1006"",""C1"",""0"",""V0"",""R1""]",bc8dad793a1bebb3be6442d4f365868e,movieFavoriteAdded,Priče koje ne daju da zaspimo S0,1776797709047,None,"{""movieId"":""106266"",""shopRef"":""18""}",1776797898879,2026-04-21 20:58:24
25,50594014213,163867001834565,1638670018345651,MOTOROLA_4,VIP1113,UTC+02:00,"[""100128"",""1006"",""C1"",""0"",""V0"",""R1""]",a3f5f66e295362bfec19f02eaf2ff58f,movieFavoriteAdded,Klub prvih žena,1776800052556,None,"{""movieId"":""114576"",""shopRef"":""18""}",1776800269310,2026-04-21 21:37:55
26,50594238788,76170002015437,761700020154371,MOTOROLA_4,VIP1113,UTC+02:00,"[""100131"",""1006"",""C1"",""0"",""V0"",""R1""]",39542e0893096eaf43e0066ff8e78bba,movieFavoriteAdded,Grinč,1776801164454,None,"{""movieId"":""131413"",""shopRef"":""3""}",1776801242253,2026-04-21 21:54:03
27,50594276425,564372001853014,5643720018530141,MOTOROLA_4,VIP1113,UTC+02:00,"[""100128"",""100131"",""1006"",""C1"",""0"",""V0"",""R1""]",47cd91786d23571cd8085fa69622a949,movieFavoriteAdded,Prva klasa – Pun gas!,1776801254762,None,"{""movieId"":""132256"",""shopRef"":""1""}",1776801408139,2026-04-21 21:56:52
28,50594627829,886082001676233,8860820016762331,MOTOROLA_4,VIP1113,UTC+02:00,"[""1006"",""C1"",""0"",""V0"",""R1""]",f068a2791d491fd68e53cd3cf53567a1,movieFavoriteAdded,Grad svetlosti,1776802730529,None,"{""movieId"":""132266"",""shopRef"":""18""}",1776802982520,2026-04-21 22:23:03
29,50594771421,760690001956220,7606900019562202,MOTOROLA_4,VIP1113,UTC+02:00,"[""1006"",""C1"",""0"",""V0"",""R1""]",57ec4973e5dd58e303db239f62988a4c,movieFavoriteAdded,Ljudi sa Menhetna S01E01,1776803437509,None,"{""movieId"":""130769"",""shopRef"":""18""}",1776803644556,2026-04-21 22:34:09

In [6]:
most_favourite_name = (
    df.groupby("name")
    .size()
    .reset_index(name="count")
    .sort_values(by="count", ascending=False)
)

most_favourite_name

                                name  count
2                     Devojačko veče      2
24              Predsednikov čovek 2      2
1                       Breht S01E01      1
0         Bekstvo iz Danemore S01E01      1
4                              Grinč      1
5                   Hari Vajld S0201      1
6   Istina o slučaju Harija Kebera S      1
7              Izjednačavanje S01E01      1
8                      Klaris S01E01      1
9                    Klub prvih žena      1
10          Ljudi sa Menhetna S01E01      1
3                     Grad svetlosti      1
11             Lovci na ukuse S01E01      1
12                       Plavi mesec      1
14        Porodica Soprano V, ep. 10      1
13         Porodica Soprano V, ep. 1      1
16         Porodica Soprano V, ep. 3      1
17         Porodica Soprano V, ep. 4      1
18         Porodica Soprano V, ep. 5      1
15         Porodica Soprano V, ep. 2      1
19         Porodica Soprano V, ep. 6      1
20         Porodica Soprano V, ep. 7      1
22         Porodica Soprano V, ep. 9      1
21         Porodica Soprano V, ep. 8      1
23           Počni već jbtnom S01E01      1
25  Priče koje ne daju da zaspimo S0      1
26             Prva klasa – Pun gas!      1
27                     Ričard roda 2      1