"mysql+pymysql://statsuser:statspass@localhost:3306/statsdb"

In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [2]:
db_uri = "mysql+pymysql://statsuser:statspass@localhost:3306/statsdb"
engine = create_engine(db_uri)

In [3]:
query = """
SELECT userId as cusRef, devId as devRef, channel as name, duration, extra, insertedTS
FROM channel_watch
"""

In [4]:
df = pd.read_sql(query, engine)

In [5]:
df_original = df.copy()

In [3]:
import sys
import os

project_root = os.path.abspath(os.path.join(os.getcwd(), "..", ".."))
sys.path.append(project_root)

from utils.metrics import (
    has_invalid_extra,
    sum_sessions,
    count_name_occurrences,
    total_channel_watch_time,
    extract_columns_from_extra
)

In [7]:
mask = df["extra"].apply(has_invalid_extra)
df = df[~mask]

In [8]:
# filtriraj nenormalne duration
df = df[df["duration"] <= 350000]

In [9]:
#vrijeme gledanja kanala
df_watch_time = sum_sessions(df)
df_watch_time

                                  devRef                name  duration
0                       3386180021773581  Arena Premium 1 HD  50170617
1                       3386180021773581      Eurosport 1 HD  34627046
2                       3730070019842081              ATV HD    181227
3                       3730070019842081              AlfaTV     19914
4                       3730070019842081               BN HD   2640602
...                                  ...                 ...       ...
688639  deea88e10a6ff36104c48b30b4922762            SciFi HD   4020819
688640  deea88e10a6ff36104c48b30b4922762           Star Life     21231
688641  deea88e10a6ff36104c48b30b4922762      Viasat History    660135
688642  deea88e10a6ff36104c48b30b4922762         Viasat Kino    854522
688643  f27376890a6ff34c2b7d09f3798c7e23             Baby TV  24253828

[688644 rows x 3 columns]

In [ ]:
top_channel = total_channel_watch_time(df_watch_time)
top_channel = top_channel.reset_index(drop=True)
top_channel

                 name  total_watch_time
0               BN HD      335041779246
1                RTRS      282537557237
2             Pink BH      260434114175
3                Prva      124627574153
4      Informer TV HD      108165692441
..                ...               ...
456       Pink Folk 1            265180
457         EroXXX HD            245551
458      Gametoon HD             198374
459  ArtHouse Filmbox            120039
460   Fast&Fun Box HD             27537

[461 rows x 2 columns]

In [11]:
device_count_df = count_name_occurrences(df_watch_time, 0)
device_count_df = device_count_df.reset_index(drop=True)
device_count_df

                 name  count
0               BN HD  29083
1                RTRS  27414
2              ATV HD  19238
3                Prva  17974
4        SUPERSTAR HD  17639
..                ...    ...
456      Gametoon HD       2
457   Fast&Fun Box HD      1
458       Pink Folk 1      1
459            TDC HD      1
460  ArtHouse Filmbox      1

[461 rows x 2 columns]

In [ ]:
df = df.rename(columns={"duration": "program_duration"}) #sesion_duration
df_extract = extract_columns_from_extra(df, "extra", ["title", "programId", "duration"])

In [20]:
df_extract = df_extract.rename(columns={"program_duration": "session_duration"})
df_extract = df_extract.reset_index(drop=True)
df_extract

,cusRef,devRef,name,session_duration,insertedTS,title,programId,duration
0,97719001571249,977190015712492,Informer TV HD,300054,2026-04-21 00:00:00,Tajne svetog pisma,68517353,5100000
1,119237001360895,1192370013608951,SUPERSTAR HD,300085,2026-04-21 00:00:00,3:10 za Jumu,68490580,7800000
2,845920001263859,8459200012638591,Pink BH,300047,2026-04-21 00:00:00,Elita 9,68565582,7200000
3,1057407003490287,105740700349028700001,RTL 2 HD,300020,2026-04-21 00:00:00,Prijatelji,68575346,1200000
4,9999527920479999,100513540,ID,300069,2026-04-21 00:00:00,Detektor laži: Rendžer Džejms Holand,68423561,7200000
...,...,...,...,...,...,...,...,...
13120159,349914001347486,3499140013474862,TV 101,300048,2026-04-21 23:59:54,Muzički program,68450637,7200000
13120160,220048001342309,2200480013423091,Euro Cinema 1,300058,2026-04-21 23:59:54,Plesom u budućnost 56,68448009,2880000
13120161,535171001224456,5351710012244561,Erotic 4,197897,2026-04-21 23:59:54,Penetrating Teenage Asshole,68594434,11820000
13120162,535171001224456,5351710012244561,Erotic 5,23941,2026-04-21 23:59:54,Severe Anal,68489139,8700000
13120163,535171001224456,5351710012244561,Erotic 7,60001,2026-04-21 23:59:54,Fresh Teenage Pussy,68593705,4920000

In [25]:
df_user = (
    df_extract
    .groupby(['devRef', 'programId', 'name', 'title', 'duration'], as_index=False)
    .agg(user_watch_time=('session_duration', 'sum'))
)

df_user = df_user.sort_values(by="user_watch_time", ascending=False)
df_user = df_user.reset_index(drop=True)

In [27]:
df_user = df_user[
    df_user['user_watch_time'] >= 0.75 * df_user['duration']
]
df_user

,devRef,programId,name,title,duration,user_watch_time
0,9574230023739171,68450873,Prijedor TV,Program Radio Prijedora,64800000,64451835
1,5582170023971901,68450873,Prijedor TV,Program Radio Prijedora,64800000,64451593
2,458780025523771,68450873,Prijedor TV,Program Radio Prijedora,64800000,64212346
3,9988370029677422,68450873,Prijedor TV,Program Radio Prijedora,64800000,63902209
4,2609670019868461,68450873,Prijedor TV,Program Radio Prijedora,64800000,63851697
...,...,...,...,...,...,...
1873999,1884690009680121,68572925,Adria TV,Na današnji dan,60000,47460
1876435,725610022521201,68572923,Adria TV,Saobraćaj,60000,46725
1876917,2883800022077312,68565819,LOL,Skrivena kamera Sexy Cam,60000,46586
1880479,200000000003607500001,68503721,Adria TV,Na današnji dan,60000,45572
1881870,9047190018389771,68594263,Red TV,Whatzuuuuup,60000,45186

In [28]:
top_titles = (
    df_user
    .groupby(['programId', 'name', 'title'])['devRef']
    .count()
    .reset_index(name='viewer_count')
    .sort_values(by='viewer_count', ascending=False)
)

top_titles

,programId,name,title,viewer_count
6140,68462975,BN HD,Dnevnik 2,8505
6130,68462970,BN HD,Dnevnik 1,5951
6142,68462976,BN HD,Zarobljena,5749
11481,68586920,RTRS,Dnevnik 2,5024
6136,68462973,BN HD,Danas u Srpskoj,4343
...,...,...,...,...
11,68422305,Disney Channel,Čarobnjaci van Vejverli Plejsa,1
10,68422304,Disney Channel,Vampirina: Tinejdžerka vampirica,1
9,68422303,Disney Channel,Mirakulus,1
8,68422300,Disney Channel,Finis i Ferb,1
7,68422299,Disney Channel,Finis i Ferb,1

In [3]:
import sys
import os

project_root = os.path.abspath(os.path.join(os.getcwd(), "..", ".."))
sys.path.append(project_root)

from processors.live_usage import process  # noqa: E402

In [4]:
live_query = """
SELECT *
FROM statistic
WHERE type = 'LiveUsage';
"""

In [5]:
live_df = pd.read_sql(live_query, engine)

In [6]:
live_df_orginal = live_df.copy()

In [7]:
live_df = process(live_df)

In [8]:
live_df['channels_by_time']

                name  total_watch_time
62             BN HD      335041779246
346             RTRS      282537557237
273          Pink BH      260434114175
329             Prva      124627574153
217   Informer TV HD      108165692441
..               ...               ...
53             BHT 1        5589129622
139  Euronews BiH HD        5404239684
94            DOX TV        5375647249
251       Naxi radio        5372430931
405   SUPERSTAR 3 HD        5268832565

[100 rows x 2 columns]

In [9]:
live_df['channels_by_users']

                  name  count
62               BN HD  26991
345               RTRS  24940
4               ATV HD  16246
328               Prva  15405
347              RTS 1  14181
..                 ...    ...
403        SUPERSTAR 2   1311
100  Discovery Channel   1300
241            Minimax   1273
184           HRT 3 HD   1269
351              RTS 3   1253

[100 rows x 2 columns]

In [10]:
live_df['top_titles']

       programId     name             title  viewer_count
6140    68462975    BN HD         Dnevnik 2          8505
6130    68462970    BN HD         Dnevnik 1          5951
6142    68462976    BN HD        Zarobljena          5749
11481   68586920     RTRS         Dnevnik 2          5024
6136    68462973    BN HD   Danas u Srpskoj          4343
...          ...      ...               ...           ...
156     68446042   ATV HD         Marketing          2210
11506   68586953    RTS 1             Vreme          2189
12755   68594381  Pink BH               DNK          2144
6497    68466174    BN HD     Muzički izlog          2106
13687   68612329     RTRS  Može i drugačije          2045

[100 rows x 4 columns]