In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [2]:
db_uri = "mysql+pymysql://statsuser:statspass@localhost:3306/statsdb"
engine = create_engine(db_uri)

In [23]:
guery = """
SELECT *
FROM statistic
WHERE type = 'NETWORK_TIMESHIFTUsage';
"""

In [24]:
df = pd.read_sql(guery, engine)

In [25]:
df.drop_duplicates()
df

,id,cusRef,devRef,devType,devModel,timeZone,cusGrRefs,ref,type,name,time,duration,extra,deliveredTS,insertedTS
0,50582124980,863974001629848,8639740016298482,KREATV_5,VIP4205,UTC+01:00,"[""100128"",""100131"",""1006"",""A0"",""C1"",""0"",""A2"",""...",341,NETWORK_TIMESHIFTUsage,Pink Comedy,1776722381409,300022,"{""title"":""Mamurluk u Bangkoku"",""genre"":""Film"",...",1776722396539,2026-04-21 00:00:00
1,50582125298,270854002646045,2708540026460451,MOTOROLA_4,VIP1113,UTC+02:00,"[""100128"",""100131"",""1006"",""C1"",""0"",""V0"",""R1""]",119,NETWORK_TIMESHIFTUsage,Narodna TV HD,1776722384633,300061,"{""title"":""DNK"",""genre"":""Zabava"",""startTime"":17...",1776722399753,2026-04-21 00:00:00
2,50582125536,986463002821269,9864630028212691,MOTOROLA_4,VIP1113,UTC+01:00,"[""100128"",""100131"",""R1"",""1006"",""C1"",""0"",""V0""]",1001101,NETWORK_TIMESHIFTUsage,Euro Cinema 4,1776722308541,102804,"{""title"":""Duhovi Ismaila"",""genre"":""Film"",""star...",1776722399129,2026-04-21 00:00:07
3,50582125716,967176002460491,9671760024604912,MOTOROLA_4,VIP1113,UTC+01:00,"[""100128"",""100131"",""R1"",""1006"",""C1"",""0"",""V0""]",33,NETWORK_TIMESHIFTUsage,Happy TV,1776722346200,300047,"{""title"":""Žena"",""genre"":""Film"",""startTime"":177...",1776722400902,2026-04-21 00:00:07
4,50582125960,9658002425996,96580024259962,MOTOROLA_4,VIP1113,UTC+02:00,"[""100128"",""100131"",""1006"",""C1"",""0"",""V0"",""R1""]",319,NETWORK_TIMESHIFTUsage,Pink Romance,1776722371616,300065,"{""title"":""Ne zaljubljuj se na prvi pogled"",""ge...",1776722403434,2026-04-21 00:00:07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34710,50595720785,9999468401359999,99994684013599994,MOTOROLA_4,VIP1113,UTC+01:00,"[""L1"",""L2"",""V0""]",400,NETWORK_TIMESHIFTUsage,History,1776808746370,300041,"{""title"":""Drevni vanzemaljci: Poreklo"",""genre""...",1776808789272,2026-04-21 23:59:51
34711,50595720810,413965001795090,4139650017950902,MOTOROLA_4,VIP1113,UTC+02:00,"[""1006"",""C1"",""0"",""V0"",""R1""]",100822,NETWORK_TIMESHIFTUsage,Pink BH,1776808761928,300051,"{""title"":""Ami G Show"",""genre"":""Entertainment"",...",1776808789590,2026-04-21 23:59:51
34712,50595721172,944811002312170,9448110023121701,MOTOROLA_4,VIP1113,UTC+01:00,"[""100128"",""100131"",""R1"",""1006"",""C1"",""0"",""V0""]",400,NETWORK_TIMESHIFTUsage,History,1776808740953,300045,"{""title"":""Drevni vanzemaljci: Poreklo"",""genre""...",1776808784933,2026-04-21 23:59:54
34713,50595721681,101249002194732,1012490021947321,MOTOROLA_4,VIP1113,UTC+01:00,"[""100128"",""100131"",""1006"",""C1"",""0"",""V0"",""R1""]",100865,NETWORK_TIMESHIFTUsage,Blic TV HD,1776808731665,264627,"{""title"":""Podkast: \""Životna priča\"""",""genre"":...",1776808791443,2026-04-21 23:59:54
34714,50595721925,969733002520448,9697330025204481,MOTOROLA_4,VIP1113,UTC+02:00,"[""100125"",""1006"",""C1"",""0"",""V0"",""R1""]",401,NETWORK_TIMESHIFTUsage,National Geographic,1776808741585,300054,"{""title"":""Narko-biznis - Najbolje scene"",""genr...",1776808794721,2026-04-21 23:59:54

In [5]:
guery = """
SELECT DISTINCT type
FROM statistic;
"""
typ = pd.read_sql(guery, engine)
typ['type'].tolist()

['CUAssetViewed',
 'LiveUsage',
 'mediaSeen_PROGRAM',
 'mediaSeen_VOD',
 'movieFavoriteAdded',
 'movieRent',
 'NETWORK_DvrUsage',
 'NETWORK_TIMESHIFTUsage',
 'PromotionShow',
 'RESTARTUsage',
 'schedulingAdded',
 'shopLoaded',
 'STARTOVERUsage',
 'VodUsageMOVIE',
 'widgetShow']

In [13]:
title_query = """
SELECT DISTINCT JSON_UNQUOTE(JSON_EXTRACT(extra, '$.title')) AS title
FROM Extra_total_watch_time
"""

df_title = pd.read_sql(title_query, engine)

In [19]:
title = df_title['title'].tolist()

In [11]:
# from collections import Counter

# duplikati = [item for item, count in Counter(title).items() if count > 1]
# print(duplikati)

['"Program Radio Prijedora"', '"Muzički program"', '"Elita 9"', '"Noćni program"', '"Review"', '"Odjava programa"', '"Program Radio Gradiške"', '"CTV Music"', '"Info kanal"', '"Poslijepodne uz RTV USK"', '"Vesti sa Srđanom Predojevićem"', '"Uranak"', '"BBC dokumentarni program"', '"Uključenje u satelitski program"', '"Dokumentarni Film"', '"Elita Pretres nedelje"', '"Non-stop LoveBox"', '"Telopi"', '"Reprizni blok"', '"Novo"', '"Lavirint tajni"', '"Dobro jutro, Srpska!"', '"Gambolov čarobno ćaknuti svet"', '"Kraj programa"', '"Elita Izbor potrčka i pretres nedelje"', '"Novo jutro"', '"Global"', '"Uključenje u program TV SAHAR"', '"Priče iz Bosne"', '"Lagalica"', '"Samo naše"', '"National Fighting Championship"', '"Aktuelnosti"', '"387 playlista"', '"Zaseda"', '"Pinkove Zvezdice"', '"TV Čorba"', '"Jutro"', '"Jutro na Blic"', '"Dobro jutro, ljubavi"', '"Kolažni zabavni program"', '"Narodna muzika"', '"Farma finale"', '"Primi me za ruku"', '"Uhvati me za ruku"', '"Muzički spotovi"', '"SuperEnduro Svetsko prvenstvo"', '"NASCAR Cup Series"', '"Snuker: SP - Šefild"', '"RAInews24"', '"Religija u službi života"', '"Veličanstveni matador"', '"Biblija"', '"Dnevnik Nove BH"', '"Beli prah"', '"Centurion FC (Cfc)"', '"WGP Kickboxing Brazil"', '"Dobar, loš, zao"', '"Zapisi pored puta"', '"Kralj Ričard"', '"Jutro za sve"', '"Illicit"', '"Pitao BIH za druga"', '"Koncert za dobro jutro"', '"Dan na dan"', '"Sarajevsko jutro"', '"Narodna izvorna muzika"', '"Slepa opsednutost"', '"Otvori oči"', '"IEM RIO"', '"Popodnevni program"', '"Dobro jutro, Srpska"', '"Večer ljubavi"', '"The Morning of Russia"', '"Video strane"', '"Popodnevne balade"', '"Ljubav u ritmu"', '"Bejzbol - MLB"', '"Viva latino"', '"Fox and Friends"', '"ESL Pro Liga"', '"PL Live"', '"Dobro jutro, Vojvodino"', '"Punkt 12 - Das RTL-Mittagsjournal"', '"IEM Rio Major"', '"Zeničko jutro"', '"TV Prodaja"', '"Seks i grad 2"', '"Ino muzika"', '"Noćne zvijezde"', '"Jutarnji program"', '"Ferocious Feet"', '"Sve osim politike"', '"Supermen"', '"Pecite sa Akisom"', '"Smrtonosno oružje"', '"Farma polufinale"', '"Ne gledam ti ja to"', '"SMS CHAT"', '"Narodni mix"', '"Ukradene duše"', '"Euronews jutro"', '"Info blok TV Vogošća & Intermezzo"', '"Domaći mix"', '"Regionalna pop muzika"', '"La hora de La 1"', '"Neprijatelj pred vratima"', '"Srećna nova \'49"', '"Kiše zemlje moje"', '"Brak je mrak"', '"Maćeha"', '"Fox Sports Africa Boxing"', '"Geo Doc"', '"FarWest"', '"Pinkove zvezde"', '"Belve"', '"Džumandži: Sledeći nivo"', '"Radio Happy"', '"Beba Bridžit Džouns"', '"Povratak Betmena"', '"Really Tight Teenage Asshole"', '"Novajlije"', '"NHL"', '"Deep Ass Fucking with Young Girls"', '"BN music produkcija - turbo folk"', '"NFL Super Bowl"', '"Košarka - NBA liga"', '"WTA 250 Hobart"', '"UFC Reloaded 324"', '"Poslednji Samuraj"', '"Ko rano rani"', '"Le Man \'66: Slavna 24 sata"', '"Story of she 2"', '"WTA 250 Rouen"', '"Teheran 43: Pokušaj atentata"', '"Svemirska odiseja 2010"', '"Noćni glazbeni program - spotovi"', '"Muzički izlog"', '"Severe Anal"', '"Prizivanje zla 2"', '"Insane Summer Swingers"', '"Povratak u budućnost"', '"Trenutak iz sna"', '"Ne zaljubljuj se na prvi pogled"', '"Dvoboj na Misuriju"', '"Vojvotkinja"', '"Lep dan u komšiluku"', '"Solista"', '"Spokoj"', '"Omiljeni par"', '"Terminator: Spasenje"', '"Hanibal"', '"Dokumentarni utorak s Avdom Huseinovićem"', '"Hari Poter i zatvorenik iz Askabana"', '"Dirty DP Chicks"', '"Večni"', '"Mrtav ugao"', '"Young Harlots: Sex Athletics"', '"The Bang Theory"', '"3:10 za Jumu"', '"Me Two"', '"Spajdermen: Povratak kući"', '"Fanatik"', '"Karate Kid 2"', '"Spajdermen: Daleko od kuće"', '"Budilnik"', '"Spajdermen: Putovanje kroz Spajder-svet"', '"Ni pet ni šest"', '"Deutschland sucht den Superstar"', '"Tokyo Twilight"', '"Mančester na moru"', '"Veliki diktator"', '"Poirot"', '"F1 Japan"', '"Mamurluk 3"', '"Džumandži: Dobrodošli u Džunglu"', '"Kralj Petar I"', '"Fresh Teenage Pussy"', '"Misija"', '"Hardcore Home Swingers"', '"Anal Swingers Exposed"', '"Elita Uživo"', '"Princesses on Anal Trails"', '"Union Pacifik"', '"Agata Kristi: Slučajevi gospođice Marpl"', '"Kućni prijatelj iz prerije"', '"TV pozorište"', '"Ne"', '"Mensch Retter"', '"Šta se upravo dogodilo"', '"Little Anal Angels"', '"World Otvoreni studio"', '"Odeljenje za maloletnike"', '"Bandit"', '"Ptice Grabljivice i fantastična emancipacija Harli Kvin"', '"Do samog kraja"', '"Lemoni sniket"', '"Wet Dirty Sluts"', '"The Sensual Rapute Of the Super Models"', '"Kauboji i vanzemaljci"', '"Stretched For Pleasure"', '"Velika crvena divizija"', '"Osveta blizanaca"', '"Iskupljenje za pljačkanje mrtvih"', '"ATV Jutro"', '"Ludo letovanje"', '"Bokser"', '"Petar Pan"', '"Božićni duhovi"', '"Bela ruža"', '"Čašica razgovora"', '"Warm wind from the North"', '"Palmeze"', '"MMA UFC Fight Night"', '"Crtani film"', '"Lesbian Sweeties In Love"', '"Un passo dal cielo"', '"Storie italiane"', '"Košarka - ABA liga"', '"Fudbal - WWin Liga BiH"', '"Fudbal - Italijanska liga"', '"Fudbal - Njemačka liga"', '"Fudbal - 2. španska liga"', '"Fudbal - Portugalska liga"', '"Kanal 6"', '"Fudbal - Engleska liga"', '"Adriatic Sport 1"', '"Fudbal: HNL"', '"ATP Masters Miami"', '"Winter Wonder Teens"', '"Košarka - Euroliga"', '"The Match"', '"TV Koreni"', '"Fudbal"', '"Pad u raj"', '"Iz vedra neba"', '"Ted"', '"Dani sreće"', '"Such A Sexpert"', '"Toto i Kleopatra"', '"Cumming To School"', '"Prvi januar"', '"Anonimni pisci"', '"Otvoreni studio - Svet u plamenu"', '"Krstarenje za Božić"', '"Isterivači duhova"', '"Rođeni za trku"', '"Fudbal - Italijanski kup"', '"Fudbal - Argentinska liga"', '"Zabavna muzika - EX YU"', '"Zabavna muzika - noviteti"', '"Košarka - Juniorska ABA Liga"', '"Specijal Svet u plamenu"', '"Fudbal - Španska liga"', '"Fudbal Njemačka 2. liga"', '"Boje uma"', '"Poslednji skaut"', '"Fudbal - Turska liga"', '"Fudbal - Grčka liga"', '"Veridba od 90 dana: U inostranstvu"', '"Odbojka - Turska liga"', '"BHT 1 uživo"', '"Mrzim čoveka u mom podrumu"', '"Jeruzalem"', '"Bekstvo iz Šošenka"', '"Misterija Aurore Tigarden: Igra mačke i miša"', '"Monstrumi iz dubina"', '"Mustang Seli"', '"Fudbal - Španski kup"', '"Korumpirani"', '"Pedeset prvih sastanaka"', '"Medeni mesec"', '"Do zvezda"', '"Fudbal: Ruska Premier Liga"', '"Fine devojke ne eksplodiraju"', '"Prva liga Srbije 2025/26"', '"Inspektor Džordž Džentli"', '"Pavle Apostol Hristov"', '"Arena Sport 1x2"', '"Fudbal - Francuska liga"', '"Glavom kroz zid"', '"Fudbal - Mozzart Bet Superliga"', '"Početi ponovo"', '"Uprkos svemu"', '"Odbojka: Superliga Srbije (Ž)"', '"Fudbal - Ruska liga"', '"Fudbal - Turski kup"', '"Dvostruka prevara"', '"Život je kocka"', '"Nedeljni konj"', '"Preživljavanje - Goli i uplašeni"', '"Mi danas"', '"Skrivena lepota"', '"America Reports"', '"Fudbal - Engleska 2. liga"', '"Anđeli i demoni"', '"Turbo folk muzika"', '"Fudbal - Superliga Srbije"', '"Zli doktor"', '"Ami G Show"', '"Zlatni momci"', '"60 Minutes"', '"Efootball EPC Liga S4"', '"Srbija on line"', '"WTA 500 Stuttgart"', '"Melodije za dušu"', '"Oko za oko"', '"Otvoreni studio - World"', '"S ljubavlju, vaša Zašećereno Zasoljena"', '"MMA UFC 22"', '"Hanuman gospodar senki"', '"Mukabela"', '"Melodrama"', '"Uteha u naručju neznanaca"', '"Cherry Girls"', '"Dnevnici zombija 2"', '"Kuharske zavrzlame"', '"Mehanika - priče iz radionica"', '"Ubilačke igre"', '"Putevi droge"', '"Ispovesti hohštaplerke iz krem društva"', '"Bitka u Ardenima"', '"Poslednja sekta"', '"Kur\'anska razglednica"', '"Ceremonija"', '"Zorom"', '"Podkast Žive reči"', '"Lopov s krova"', '"Amerikanac"', '"Kratke priče"', '"Kulagins"', '"Otvoreni studio plus"', '"Sing meinen Song - Das Tauschkonzert"', '"Armes Deutschland - Stempeln oder abrackern?"', '"Odbojka: Prvenstvo BIH za pionirke"', '"Fudbal - Kup Republike Srpske"', '"Repriza Programa"', '"Rukomet - Premijer liga BiH"', '"Реальное кино"', '"Press"', '"Obred"', '"Поколение Евромайдан"', '"Odbojka - Premijer liga (m)"', '"Odbojka_ Prvenstvo Republike Srpske (Ž)"', '"Gotika"', '"Drumska kafana"', '"Секретные радиопереговоры армии РФ под Киевом"', '"Počasni građanin"', '"America\'s Newsroom"', '"Astro show"', '"Ministarstvo nedžentlmenskog ratovanja"', '"Gladijator"', '"Fresh Faces"', '"Večeras sa vama"', '"Konjički sport: Svetski tur šampiona - Meksiko Siti"', '"Fight Network"', '"Young Harlots - School Report"', '"Objekat"', '"Opasan poziv"', '"Igrani film"', '"Hot anal fantasies"', '"Moj tajni milijarder"', '"Zona press"', '"Plen"', '"Američki prijatelj"', '"Privatno bankarstvo"', '"Poslednji sneg proleća"', '"Ne diši 2"', '"Siromašni ali bogati 2"', '"Čuvari planete"', '"Tornado 2"', '"Timbuktu"', '"Enfusion"', '"Farma Izbacivanje"', '"Kil Bil 2"', '"Jesen u vinogradu"', '"Play TV"', '"Žena mačka"', '"Mrtvačnica"', '"Sledeća stanica Raj"', '"Sedam dolara za ubistvo"', '"Mamurluk u Bangkoku"', '"Tito i ja"', '"Maskenbal"', '"Mamin svet"', '"Biciklizam: Serija PRO - Tur Alpa (M)"', '"Otmica u metrou 123"', '"Il commissario Montalbano"', '"Kako ukrasti nevestu"', '"Služio sam engleskog kralja"', '"The Trial"', '"Cena lojalnosti"', '"Der Trödeltrupp - Das Geld liegt im Keller"', '"Cijena odanosti"', '"Filmski program"', '"30 and married"', '"La volta buona"', '"E.T. the Extra-Terrestrial"', '"Pet"', '"Jerusalim"', '"Požuda"', '"Audicija"', '"150 minuta"', '"Četvrti zid"', '"Girls Out Camping"', '"Boj na Kosovu"', '"Petrijin venac"', '"Tusta"', '"Sedam godina vernosti"', '"Lovely Little Lesbians"', '"Novinar"', '"Napola"', '"Teens Just Wanna Have Fun"', '"Natural Beauties"', '"Ples malog pingvina"', '"Interracial"', '"Variola vera"', '"Čarolija limunskih kapi"', '"Reportaža"', '"Heidi"', '"Dobar dan, tugo"', '"Upoznajte Dejva"', '"Duhovi Ismaila"', '"Turneja"', '"Pismo - glava"', '"Veridba od 90 dana: Period upoznavanja"', '"Charade"', '"Čarolija limunskih koktela"', '"Lope"', '"Zimska palača"', '"Put"', '"MILF Tan Lines"', '"Rosamund Pilčer"', '"Oslobađanje"', '"Fucking My Son\'s Friend"', '"Zimski dvorac"', '"Baba"', '"Premijera vikend specijal"', '"Kolaž kratke priče sa terena"', '"Mama Roma"', '"Digstaun"', '"Irina Palm"', '"Jingled All the Way"', '"Kastrovi špijuni"', '"Nije ovo tek još jedan tamo neki film"', '"Black fuckers"', '"Stotinu koraka"', '"Ljubav ispod zlatnog bora"', '"Savršen osećaj"', '"Veliko hrabro predivno putovanje"', '"Povratak otpisanih"', '"Milf advantures"', '"Nestali za 60 sekundi"', '"MILF Imports"', '"Posle sumraka"', '"Doktor Rej i đavoli"', '"Igra chefova"', '"Šaft"', '"U zasedi"', '"Već viđeno"', '"Puls Srbije"', '"Uskršnje cvetanje"', '"Dan po dan"', '"Uskršnji cvat"', '"Kralj u Njujorku"', '"Legenda o kapiji pakla"', '"Agorà"', '"Pod sjajem zvezda"', '"Poštanska kočija: Priča Teksas Džeka"', '"Pakao iz \'63"', '"Er Amerika"', '"Kuća od karata"', '"Vječni ciklus komedije: Tigre"', '"Underground Boxing Night"', '"Debeli i mršavi"', '"That Evening Sun"', '"Ip Man 3"', '"Ljubav i Meri"', '"The War Is Over"', '"Dohvati nebo"', '"Tuzla danas"', '"Creation"', '"Gorko-slatko"', '"Kraljeva igra"', '"Nikšićko popodne"', '"Peti leptir"', '"Maks Pejn"', '"Boobs Exposed By Black Men"', '"Getting Threed"', '"Zli poručnik: Nju Orleans"', '"Planinari"', '"Planeta majmuna: Početak"', '"Rada sam"', '"TV Teatar"', '"Inspektor Morse"', '"Ispod sveta"', '"Grateful For Grannies"', '"Kralj New Yorka"', '"Najbolje božićno takmičenje ikad"', '"Komik Sans"', '"Prekobrojna"', '"Srebrna zvezda"', '"Plan bekstva"', '"Šarenica"', '"In3gantno"', '"12 časova agonije"', '"Živeti"', '"Hartz Rot Gold - Armutskarte Deutschland"', '"Rat Čarlija Vilsona"', '"Zavjet"', '"Igra chefova - novi show"', '"Laf u srcu"', '"Centar dana"', '"Majstori, majstori"', '"Rane"', '"Kolegijum 1"', '"Ljubavna priča"', '"Ja, ti i Dupri"', '"Otok ljubavi"', '"Klik za savršeni život"', '"Dva metra iznad zemlje"', '"Minecraft Film"', '"Pesnica Pravde 2: Smrtonosni Izbor"', '"Vrati se"', '"Bolničari"', '"Torpedo"', '"Regresa"', '"Kimia"', '"Bez presedana"', '"Uncle Nino"', '"Danteov vrh"', '"Patnja i ozdravljenje"', '"Čarlijev svet"', '"How to Train Your Dragon 2"', '"Dobra zemlja"', '"Simon sa planine"', '"Trophy Wives"', '"Kolažni program"', '"Džekpot!"', '"Srećne okolnosti"', '"Kupi mi Eliota"', '"Kriminalno obrazovanje"', '"Kobna igra"', '"Neobični slučaj Bendžamina Batona"', '"Usijanje"', '"Ministarstvo vremena"', '"Leto u decembru"', '"Knjiga života"', '"Maske"', '"Ostinlend"', '"Preparator"', '"La vita in diretta"', '"Intervju"', '"Crno na bijelo"', '"Sedmi sin"', '"Torente 2: Misija u Marbelji"', '"Tesna koža"', '"Kamiondžije ponovo voze"', '"Sabirni centar"', '"Tri boje crveno"', '"Tren"', '"Hajde da razgovaramo"', '"Mašinovođa"', '"Popodne"', '"Godina kada mi je mama bila Doli Parton"', '"Na sprovodu"', '"Šape gneva: Legenda o Henku"', '"Ugovor"', '"Velika isplata"', '"Tanka linija smrti"', '"Bubamara"', '"Naš svet"', '"Rain"', '"U trci s kometama"', '"50 prvih sastanaka"', '"Frieda"', '"Hurricane Season"', '"Jungelicious (Hard)"', '"Šerif i dečak iz svemira"', '"Sheer Pleasure"', '"Otpisani"', '"I Bog stvori kafansku pevačicu"', '"Teorije zavera"', '"Pogrešan korak"', '"Ruke Trboseka"', '"Koncert"', '"Čas istorije"', '"Tesna koža 1"', '"Breza"', '"Špica"', '"Osamljenik"', '"Crvena zemlja"', '"Anđeo čuvar"', '"Crveni kofer"', '"Žena za sva vremena"', '"Dotiki"', '"Добри вечар Войводино"', '"Čuvaj se... komšije"', '"Muzički specijal"', '"Dobitna kombinacija"', '"Posle ručka"', '"Obračun u kazino Kabareu"', '"Narodni poslanik"', '"Info dan"', '"Max Cloud"', '"Dobro jutro Hercegovino"', '"Kolegijum 2"', '"Višnja na Tašmajdanu"', '"Oštećen"', '"Izgubljeni drim tim"', '"Tasteless LoL-uje"', '"Duh"', '"Vruće mleko"', '"Endurance moto trka - 24 sata Le Mana"', '"Vaterpolo - Liga Prvaka"', '"Čitulja za Eskobara"', '"Izdvajamo uranak"', '"Criminal Activities"', '"Sarezza Minecraft"', '"Razgovori"', '"Profesor Babic - The Elder Scrolls Iv: Oblivion"', '"Naše jutro"', '"The Sorcerer and the White Snake"', '"Kada Migzi Postane Senka - Assassin\'s Creed Shadows"', '"Kada ljubav izvire"', '"Hit lista"', '"Kad te zaskoči ljubav"', '"Sasvim iskreno"', '"Želim da ti kažem"', '"Vamps"', '"Red Bull: Blood Road"', '"Dječiji program"', '"Loše komšije 2"', '"Legendarni Tkdspale - Apex Legends"', '"Best egzotik merigold hotel"', '"Kralj boraca"', '"Drevni vanzemaljci: Poreklo"', '"Naše Popodne"', '"Brak na prvu (Australija)"', '"Ted - izgubljeni pustolov"', '"Jerked by teacher"', '"Bratstvo"', '"Submissive lesbians"', '"Priča iz Bronksa"', '"Migz1 - Clair Obscur: Expedition 33"', '"Little black girls"', '"Young teen nurses"', '"Opa Show"', '"Moto GP: Brazil"', '"Idemo, idemo"', '"MILFs With Tight Pinks!"', '"Inch big black anal"', '"I Don\'t Know How She Does It"', '"Sevdalinka u srcu"', '"Arena Pubg Sa Mausom"', '"Boys abused"', '"Anal teachers"', '"Dani Daniels girl perversions"', '"Groupsex Gazongas"', '"Boners for schoolgirls"', '"19YOs Nailed By Best Friend\'s Dad!"', '"Younger Men Tag Cougars"', '"Orange is the new rack"', '"BellaMà"', '"Milf cops sex squad"', '"Sexy cheerleader sluts"', '"GILFs Crave Big-Pole Threeways"', '"Two Rods Thrust 3Way 18YOs!"', '"Ženski kutak"', '"Stacked Lesbians Lick & Scissor"', '"Koni Plank Potencijal buke"', '"Neumoljivi"', '"Zvižduk u osam"', '"Filmsko veče na TV Zenica"', '"Grinč"', '"Extra - Das RTL Magazin"', '"Lost in brazzers"', '"Porodica Serano"', '"Podcast iz srca Romanije"', '"Teorija velikog praska"', '"Horizonti zapada"', '"Kroz dolinu smrti"', '"Biciklizam - Milano-San Remo (m)"', '"Naš gost"', '"Film"', '"Vikend vizija"', '"10 Best: Horny 18YO Stepdaughters #2"', '"Pusti snovi"', '"Devojka"', '"Hype zvezde"', '"35 godina grupe \\"Alisa\\": Najbolje iz Zemlje čuda"', '"TV prodaja: Biostile - Vaše zdravlje, naša briga"', '"A što ne bi moglo"', '"Ko živ ko mrtav"', '"Zajednička nit"', '"Abot i Kostelo sreću nevidljivog čoveka"', '"Zavičaju mili raju"', '"Zarobljena"', '"Art School"', '"Afternoon Orgasms"', '"Bitno"', '"Nulta tolerancija: Oko za oko"', '"Idemo dalje"', '"Guido Superstar: The Rise of Guido"', '"Herkul u Izgubljenom kraljevstvu"', '"Herkul i Amazonke"', '"Lick"', '"Ratnik oluje"', '"Odred duhova"', '"Spužva Bob Skockani"', '"Pod sivim nebom"', '"Zli mrtvi"', '"Zamka u Hong Kongu"', '"True Smile"', '"Gvido superstar: Gvidov uspon"', '"BN Koktel"', '"Božićna potraga"', '"Đavolja noć"', '"U potrazi za fotografom"', '"Sa Ivonom na ti"', '"RTL Danas"', '"Sećaš li se onog sata"', '"Ciguenas"', '"The Fabulous Dorseys"', '"Veliko ništa"', '"Kroz stene i oblake"', '"Pregovarač"', '"Swing night"', '"DD blondes do boys"', '"18YO Daughter Swaps & Slams"', '"Departure"', '"Busty Amateurs Want Big Dongs in Tight Places"', '"Evening with Vladimir Solovyov"', '"Raw Instinct"', '"Bing Bunny"', '"Nemačka"', '"Reflex"', '"Neka druga žena"', '"Sucked Off on A Service Call"', '"Baštovan"', '"Vragolanka"', '"Tiny Tittie Teens"', '"Ore 14"', '"Three of a Kind"', '"Ja sam iz Krajine, zemlje kestena"', '"Hot Roommate Sucked Me?!"', '"Trenutak nestajanja"', '"Gusari koji ništa ne rade"', '"Petite HD Porn 16 Eye Candy"', '"Tombston Rašomon"', '"Grešnici"', '"18+ Amateur GFs: Hot and Hungry For Dong"', '"Oops I Did Your Dad 2"', '"Dnevnik 1"', '"Pljačka pred Božić"', '"Kad svane dan"', '"Van dometa"', '"Partizanske priče"', '"Kroz granje nebo"', '"Otvoreni mikrofon"', '"Restoran"', '"Laureus, svetske sportske nagrade"', '"Život na škotskoj farmi"', '"Dokazano Džonatan"', '"Klijent"', '"Opasne veze"', '"Bivši"', '"Ananas ekspres"', '"Leteći mačevi zmajeve kapije"', '"Istine i laži"', '"Ejs Ventura: Detektiv za kućne ljubimce"', '"Projekat Dinosaur"', '"Krvoproliće"', '"Izgubljen na planini"', '"Spuner"', '"Banjalučkim korzom"', '"33 fotografije iz geta"', '"Zlatno srce"', '"Među sjenkama"', '"Predstavljanje knjige"', '"Telediario Matinal"', '"Juggs! Anal! Squirting!"', '"Farma pregled dana"', '"L\'Eredità"', '"XXI Secolo: Quando il presente diventa futuro"', '"Gang sa Su Perkins"', '"Dan Zastave"', '"Survivor"', '"Zlatni kavez"', '"Ništa sveto"', '"Nevidljiva devojka"', '"Elita Pregled dana"', '"Stream Nation"', '"Impijevo ostrvo"', '"Sigi, opasni maloletni haker"', '"3 x DA"', '"Mala škola Rokenrola - I Mila i violina i RnR"', '"Na prvom mestu"', '"Penetrating Teenage Asshole"', '"Ljubav dolazi kasnije"', '"Dnevnik 2"', '"Tenis - Australian Open"', '"Dobro jutro, Bosno i Hercegovino!"', '"VOX POPULI"', '"Velika i mala stvorenja"', '"Blic dan"', '"Boks"', '"Početak dana"', '"Visok intelektualni potencijal"', '"Drugi svetski rat - bitke za Evropu"', '"Panorama"', '"U fabrici"', '"Farma"', '"Restart"', '"Svitanje"', '"Večera za 5"', '"Kampf der RealityAllstars"', '"The Ghost Writer"', '"Bolnica inkognito"', '"Moto 3: Brazil"', '"Moto 2: Brazil"', '"Košarka Euroliga"', '"Alisa u zemlji čudesa"', '"Superbajk - Holandija"', '"Il Processo al 90°"', '"Perspektiva"', '"Radio talas"', '"My First Threesome"', '"Bela Lugosi Meets a Brooklyn Gorilla"', '"Glas"', '"Rat bendova"', '"Jubilej gospodina Ikla"', '"Smrt u raju"', '"Žene"', '"Krv nije voda"', '"Oliver Tvist"', '"Premijera"', '"Zemlja vukova"', '"Princeza i zmaj"', '"Anatane"', '"Gang Bang Fever"', '"Dvorac: Sam svoj majstor"', '"DNK"', '"Mattina 24"', '"Šoping holičarke"', '"MasterChef"', '"Glasno i jasno"', '"Kiriku i divlje životinje"', '"Bejblejd X"', '"Nacionalni dnevnik"', '"Majstorski ciklus: Vladarski dosezi"', '"Kraljica ritma"', '"Podkast: \\"Životna priča\\""', '"SPKD Prosvjeta - Vaskršnji koncert"', '"Afrika: Budućnost"', '"Optuženi: Pedofili u školi"', '"Nacisti - niti zla"', '"Gospođica Skarlet"', '"Moć Sunčevog sistema"', '"Umjetnost zločina"', '"Polarotor"', '"Borbene linije"', '"Drugi svetski rat: pakao na zemlji"', '"Pogrešan čovjek"', '"Berlin - Tag & Nacht"', '"Slugtera"', '"News"', '"TV serija"', '"To \\"Bema\\" Mrkonjić grad 10 godina 2018."', '"To \\"Bema\\" Banja Luka 10 godina"', '"Adorable Girls"', '"Hronologija jednog bombardovanja"', '"Brak na neviđeno"', '"Najužasnije vremenske neprilike"', '"Vrijeme je za jazz"', '"Inspektor Rex"', '"Muzički podsetnik"', '"Povuci ručnu"', '"Evolucija"', '"Klopka lju

In [ ]:
import sys
import os

project_root = os.path.abspath(os.path.join(os.getcwd(), "..", ".."))
sys.path.append(project_root)

from utils.metrics import extract_from_json
from processors.network_timeshift_usage import process

In [27]:
df = extract_from_json(df, 'extra', 'title', 'title')
df['title']

0                    Mamurluk u Bangkoku
1                                    DNK
2                         Duhovi Ismaila
3                                   Žena
4        Ne zaljubljuj se na prvi pogled
                      ...
34710        Drevni vanzemaljci: Poreklo
34711                         Ami G Show
34712        Drevni vanzemaljci: Poreklo
34713           Podkast: "Životna priča"
34714      Narko-biznis - Najbolje scene
Name: title, Length: 34715, dtype: str

In [6]:
most_recorded_name = process(df)

most_recorded_name

                name  count
32             BN HD    395
108             RTRS    288
101             Prva    243
88           Pink BH    192
75       Kurir TV HD    177
..               ...    ...
59   FilmBox Premium      1
115       RTS Trezor      1
112            RTS 3      1
103       Prva World      1
109        RTRS Plus      1

[135 rows x 2 columns]

In [ ]:
most_recorded = (
    df
    .groupby(['devRef','name','extra'], as_index=False)
    .agg(total_watch_time=('duration', 'sum'))
    .sort_values(by='total_watch_time', ascending=False)
)

most_recorded

,devRef,name,extra,total_watch_time
2376,4757870011694801,Arena Adrenalin,"{""title"":""SuperEnduro Svetsko prvenstvo"",""genr...",51547808
105,10255420032177962,Pink Movies,"{""title"":""Uprkos svemu"",""genre"":""Film"",""startT...",46329224
4923,99995612547699991,FTV HD,"{""title"":""Dobro jutro, Bosno i Hercegovino!"",""...",43604833
1843,3184340026049292,Pink BH,"{""title"":""Kuća od srca"",""genre"":""Zabava"",""star...",43207228
1792,31371900089306200002,AMC,"{""title"":""Van dometa"",""genre"":""Film"",""startTim...",43204892
...,...,...,...,...
4001,9130510019689993,NickToons,"{""title"":""Pingvini s Madagaskara"",""genre"":""Ost...",10196
2972,700340023468701,National Geographic,"{""title"":""Drugi svetski rat: Tajne iz vazduha""...",10146
1449,2770210012569981,BN HD,"{""title"":""Crno na bijelo"",""genre"":""Dokumentarn...",10129
603,1554260027147381,Ona TV HD,"{""title"":""Put ka sebi"",""genre"":""Vijesti"",""star...",10106
2604,5392970007991441,BN HD,"{""title"":""Dnevnik 2"",""genre"":""Dokumentarne vij...",10085

In [8]:
top_channel = (
    most_recorded_name
    .groupby('name')['devRef']
    .nunique()
    .reset_index(name='device_count')
    .sort_values(by='device_count', ascending=False)
)

top_channel = top_channel.reset_index(drop=True)
top_channel

                name  device_count
0              BN HD           395
1               RTRS           288
2               Prva           243
3            Pink BH           192
4        Kurir TV HD           177
..               ...           ...
130  FilmBox Premium             1
131       RTS Trezor             1
132            RTS 3             1
133       Prva World             1
134        RTRS Plus             1

[135 rows x 2 columns]

In [9]:
import json

def extract(x):
    try:
        d = json.loads(x) if x else {}
        return (
            d.get('programId'),
            d.get('title'),
        )
    except:  # noqa: E722
        return (None, None)

In [10]:
df_tmp = df[['devRef', 'name', 'duration', 'extra']].copy()

df_tmp[['program_id', 'title']] = pd.DataFrame(
    df_tmp['extra'].apply(extract).tolist(),
    index=df_tmp.index
)

In [11]:
df_tmp = df_tmp.drop(columns=['extra'])
df_tmp = df_tmp.reset_index(drop=True)
df_tmp

,devRef,name,duration,program_id,title
0,8639740016298482,Pink Comedy,300022,68565604,Mamurluk u Bangkoku
1,2708540026460451,Narodna TV HD,300061,68565444,DNK
2,9864630028212691,Euro Cinema 4,102804,68422852,Duhovi Ismaila
3,9671760024604912,Happy TV,300047,68504516,Žena
4,96580024259962,Pink Romance,300065,68565914,Ne zaljubljuj se na prvi pogled
...,...,...,...,...,...
34710,99994684013599994,History,300041,68451974,Drevni vanzemaljci: Poreklo
34711,4139650017950902,Pink BH,300051,68594409,Ami G Show
34712,9448110023121701,History,300045,68451974,Drevni vanzemaljci: Poreklo
34713,1012490021947321,Blic TV HD,264627,68585337,"Podkast: ""Životna priča"""
34714,9697330025204481,National Geographic,300054,68586431,Narko-biznis - Najbolje scene

In [12]:
df_tmp = (
    df_tmp
    .groupby(['devRef', 'name', 'program_id', 'title' ], as_index=False)
    .agg(total_watch_time=('duration', 'sum'))
)

df_tmp

,devRef,name,program_id,title,total_watch_time
0,10000000000000401,RTS Drama,68526264,Lako je Raletu,1260184
1,10000000000000401,RTS Drama,68526265,Sumnjiva lica,59331
2,10000000000001091,Agro TV,68465376,Dobra zemlja,1140217
3,10003930029825691,UNA TV HD,68468042,Esmeralda,3242106
4,10003930029825691,UNA TV HD,68468043,Zabranjena ljubav,3008883
...,...,...,...,...,...
4996,99999892063299992,HRT 2 HD,68481157,Graditelji sutrašnjice,2521042
4997,99999892063299992,HRT 2 HD,68585473,Bandit,29436
4998,d645bd2c7f0000017d8d0a28e4992279,BN HD,68446799,Zapisi pored puta,13805
4999,deea88e10a6ff36104c48b30b4922762,HBO 2,68461877,Lopov s krova,1620440
5000,deea88e10a6ff36104c48b30b4922762,HBO 2,68461878,Holivud na snimanju,30916

In [13]:
df_tmp = (
    df_tmp
    .groupby(['program_id','name', 'title'])['devRef']
    .nunique()
    .reset_index(name='device_count')
    .sort_values(by='device_count', ascending=False)
)

df_tmp

,program_id,name,title,device_count
300,68450943,Prva,Igra sudbine: Ljubav nakon greha,138
405,68462976,BN HD,Zarobljena,111
1272,68603181,RTL HD,Divlje pčele,85
1083,68591863,Kurir TV HD,Sulejman Veličanstveni,77
1139,68593656,BN HD,Crno na bijelo,74
...,...,...,...,...
10,68424321,Nick Jr.,Barbapapa i porodica,1
9,68424318,Nick Jr.,Barbapapa i porodica,1
8,68424229,National Geographic,Černobilj: Unutar katastrofe,1
7,68423061,FilmBox Stars,Ti si na potezu,1
6,68422852,Euro Cinema 4,Duhovi Ismaila,1