In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [2]:
db_uri = "mysql+pymysql://statsuser:statspass@localhost:3306/statsdb"
engine = create_engine(db_uri)

guery = """
SELECT *
FROM statistic
WHERE type = 'movieRent';
"""

In [3]:
df = pd.read_sql(guery, engine)

In [4]:
df.drop_duplicates()
df

,id,cusRef,devRef,devType,devModel,timeZone,cusGrRefs,ref,type,name,time,duration,extra,deliveredTS,insertedTS
0,50582170219,1029982003263289,102998200326328900002,MOTOROLA_4,VIP1113,UTC+02:00,"[""1006"",""C1"",""0"",""10010"",""V0"",""R1""]",1551649eebddfb5a07c930498a260e32,movieRent,Viktorijus S01E06,1776722330189,None,"{""title"":""Viktorijus S01E06"",""shopRef"":""FOKUSO...",1776722622854,2026-04-21 00:03:44
1,50582173572,470206002801489,4702060028014891,MOTOROLA_4,VIP1113,UTC+02:00,"[""100128"",""E0"",""1006"",""C1"",""0"",""V0"",""R1""]",bed69e91a581b75a6e30e9c2ddaa1f0e,movieRent,Savršeni Božić,1776722394187,None,"{""title"":""Savršeni Božić"",""shopRef"":""FOKUSON_S...",1776722635676,2026-04-21 00:04:02
2,50582175605,536987002112666,5369870021126661,MOTOROLA_4,VIP1113,UTC+02:00,"[""1006"",""C1"",""0"",""10010"",""V0"",""R1""]",da047c62f6bebcb451b3100f4c40577a,movieRent,Tvorac,1776722372956,None,"{""title"":""Tvorac"",""shopRef"":""FOKUSON_SHOP_3"",""...",1776722645335,2026-04-21 00:04:12
3,50582177690,848469001793378,1002740,MOTOROLA_4,VIP1113,UTC+01:00,"[""C6"",""1006"",""0"",""10010"",""V0"",""R1""]",a3bc398868c574f88e074f53f2a3bf2b,movieRent,"Kuća zmaja II, ep. 08",1776722418119,None,"{""title"":""Kuća zmaja II, ep. 08"",""shopRef"":""FO...",1776722655510,2026-04-21 00:04:22
4,50582181374,984962002810319,9849620028103193,MOTOROLA_4,VIP1113,UTC+02:00,"[""100128"",""1006"",""C1"",""0"",""V0"",""R1""]",f715ba418db9c53d044e8ce2c1c7f732,movieRent,Misterija Porodice Hanter S02E06,1776722581709,None,"{""title"":""Misterija Porodice Hanter S02E06"",""s...",1776722673279,2026-04-21 00:04:43
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
570,50595634285,949882002354254,9498820023542541,MOTOROLA_4,VIP1113,UTC+02:00,"[""100131"",""1006"",""C1"",""0"",""V0"",""R1""]",28481342084fe4f79978f6cb5790eb96,movieRent,Samarićanin,1776807995290,None,"{""title"":""Samarićanin"",""shopRef"":""FOKUSON_SHOP...",1776808249300,2026-04-21 23:50:57
571,50595664373,74589001949075,745890019490752,MOTOROLA_4,VIP1113,UTC+02:00,"[""100128"",""1006"",""C1"",""0"",""V0"",""R1""]",9115859d2ce738c9e24feecad9624263,movieRent,Monmartr S01E01,1776808426710,None,"{""title"":""Monmartr S01E01"",""shopRef"":""FOKUSON_...",1776808428583,2026-04-21 23:53:55
572,50595682262,1025188003213686,1025188003213686345,KREATV_5,VIP4205,UTC+02:00,"[""1006"",""C1"",""0"",""V0"",""R1""]",aeca26e40fe43dc636c1d2776b714a18,movieRent,"Štreberi II, ep. 18",1776808395709,None,"{""title"":""Štreberi II, ep. 18"",""shopRef"":""FOKU...",1776808538083,2026-04-21 23:55:47
573,50595710858,169914002472516,1699140024725161,MOTOROLA_4,VIP1113,UTC+01:00,"[""100128"",""R1"",""1006"",""C1"",""0"",""V0""]",bfdc2e07d4096d4628e598cb3c7f04bb,movieRent,Mamice se troše kao od šale,1776808669202,None,"{""title"":""Mamice se troše kao od šale"",""shopRe...",1776808727827,2026-04-21 23:58:48
574,50595718979,523772002412916,5237720024129162,MOTOROLA_4,VIP1113,UTC+01:00,"[""R1"",""1006"",""C1"",""0"",""V0""]",6790cfd749b167ec8f688edcd2c18942,movieRent,"Euforija III, ep. 02",1776808673066,None,"{""title"":""Euforija III, ep. 02"",""shopRef"":""FOK...",1776808769163,2026-04-21 23:59:42

In [5]:
most_rent_name = (
    df.groupby("name")
    .size()
    .reset_index(name="count")
    .sort_values(by="count", ascending=False)
)

most_rent_name

                                 name  count
11   Avatar: Poslednji vladar vetrova     19
72               Euforija III, ep. 02     14
88                    From IV, ep. 01     11
377                            Tvorac      7
80                              Fokus      6
..                                ...    ...
25         Bilo jednom... u Holivudu       1
26             Božić u carstvu cipela      1
27             Bruno Prangija, ep. 01      1
28             Bruno Prangija, ep. 02      1
3      Aktivacija TV-To-Go aplikacije      1

[446 rows x 2 columns]