In [1]:
import pandas as pd

In [2]:
OUTPUT_DIR = r"C:\Users\radet\Praksa\automatisation\output"

In [3]:
import os
import sys

In [4]:
parent_dir = os.path.dirname(os.getcwd())
sys.path.append(parent_dir)

In [5]:
from utils.metrics import has_invalid_extra
from utils.load import load_data, optimize_dataframe, load_event_data

In [6]:
import pyarrow as pa
import pyarrow.parquet as pq

In [31]:
print("Loading data in chunks...")

os.makedirs(OUTPUT_DIR, exist_ok=True)

writers = {}

total_before = 0
total_after = 0

for i, chunk in enumerate(load_data(chunksize=10_000)):
    chunk = optimize_dataframe(chunk)

    total_before += len(chunk)

    mask = chunk["extra"].map(has_invalid_extra)
    chunk = chunk.loc[~mask].copy()

    if chunk.empty:
        del chunk, mask
        continue

    total_after += len(chunk)

    chunk["insertedTS"] = pd.to_datetime(chunk["insertedTS"])
    chunk["event_date"] = chunk["insertedTS"].dt.date.astype(str)

    for event_date, df_date in chunk.groupby("event_date"):
        file_path = f"{OUTPUT_DIR}/iptv_{event_date}.parquet"

        df_date = df_date.drop(columns=["event_date"])

        table = pa.Table.from_pandas(
            df_date,
            preserve_index=False,
        )

        if event_date not in writers:
            writers[event_date] = pq.ParquetWriter(
                file_path,
                table.schema,
            )

        writers[event_date].write_table(table)

        print(
            f"Chunk {i}, date={event_date}: rows={len(df_date)}"
        )

        del df_date, table

    del chunk, mask

for writer in writers.values():
    writer.close()

if not writers:
    raise ValueError("No valid rows after cleaning")

print(f"Rows before cleaning: {total_before}")
print(f"Rows after cleaning: {total_after}")
print(f"Saved parquet files to: {OUTPUT_DIR}")

Loading data in chunks...

Chunk 0, date=2026-05-20: rows=9911
Chunk 1, date=2026-05-20: rows=9915
Chunk 2, date=2026-05-20: rows=9920
Chunk 3, date=2026-05-20: rows=9919
Chunk 4, date=2026-05-20: rows=9919
Chunk 5, date=2026-05-20: rows=9916
Chunk 6, date=2026-05-20: rows=9918
Chunk 7, date=2026-05-20: rows=9923
Chunk 8, date=2026-05-20: rows=9926
Chunk 9, date=2026-05-20: rows=9925
Chunk 10, date=2026-05-20: rows=9919
Chunk 11, date=2026-05-20: rows=9918
Chunk 12, date=2026-05-20: rows=9915
Chunk 13, date=2026-05-20: rows=9913
Chunk 14, date=2026-05-20: rows=9896
Chunk 15, date=2026-05-20: rows=9906
Chunk 16, date=2026-05-20: rows=9908
Chunk 17, date=2026-05-20: rows=9901
Chunk 18, date=2026-05-20: rows=9911
Chunk 19, date=2026-05-20: rows=9918
Chunk 20, date=2026-05-20: rows=9909
Chunk 21, date=2026-05-20: rows=9934
Chunk 22, date=2026-05-20: rows=9950
Chunk 23, date=2026-05-20: rows=9958
Chunk 24, date=2026-05-20: rows=9948
Chunk 25, date=2026-05-20: rows=9949
Chunk 26, date=2026-05-20: rows=9945
Chunk 27, date=2026-05-20: rows=9945
Chunk 28, date=2026-05-20: rows=9951
Chunk 29, date=2026-05-20: rows=9951
Chunk 30, date=2026-05-20: rows=9952
Chunk 31, date=2026-05-20: rows=9953
Chunk 32, date=2026-05-20: rows=9953
Chunk 33, date=2026-05-20: rows=9961
Chunk 34, date=2026-05-20: rows=9962
Chunk 35, date=2026-05-20: rows=9946
Chunk 36, date=2026-05-20: rows=9949
Chunk 37, date=2026-05-20: rows=9933
Chunk 38, date=2026-05-20: rows=9946
Chunk 39, date=2026-05-20: rows=9951
Chunk 40, date=2026-05-20: rows=9954
Chunk 41, date=2026-05-20: rows=9958
Chunk 42, date=2026-05-20: rows=9950
Chunk 43, date=2026-05-20: rows=9953
Chunk 44, date=2026-05-20: rows=9956
Chunk 45, date=2026-05-20: rows=9960
Chunk 46, date=2026-05-20: rows=9939
Chunk 47, date=2026-05-20: rows=9943
Chunk 48, date=2026-05-20: rows=9938
Chunk 49, date=2026-05-20: rows=9955
Chunk 50, date=2026-05-20: rows=9938
Chunk 51, date=2026-05-20: rows=9957
Chunk 52, date=2026-05-20: rows=9958
Chunk 53, date=2026-05-20: rows=9954
Chunk 54, date=2026-05-20: rows=9958
Chunk 55, date=2026-05-20: rows=9961
Chunk 56, date=2026-05-20: rows=9957
Chunk 57, date=2026-05-20: rows=9944
Chunk 58, date=2026-05-20: rows=9951
Chunk 59, date=2026-05-20: rows=9943
Chunk 60, date=2026-05-20: rows=9961
Chunk 61, date=2026-05-20: rows=9947
Chunk 62, date=2026-05-20: rows=9953
Chunk 63, date=2026-05-20: rows=9960
Chunk 64, date=2026-05-20: rows=9950
Chunk 65, date=2026-05-20: rows=9956
Chunk 66, date=2026-05-20: rows=9960
Chunk 67, date=2026-05-20: rows=9955
Chunk 68, date=2026-05-20: rows=9942
Chunk 69, date=2026-05-20: rows=9951
Chunk 70, date=2026-05-20: rows=9944
Chunk 71, date=2026-05-20: rows=9961
Chunk 72, date=2026-05-20: rows=9949
Chunk 73, date=2026-05-20: rows=9956
Chunk 74, date=2026-05-20: rows=9960
Chunk 75, date=2026-05-20: rows=9955
Chunk 76, date=2026-05-20: rows=9965
Chunk 77, date=2026-05-20: rows=9959
Chunk 78, date=2026-05-20: rows=9965
Chunk 79, date=2026-05-20: rows=9951
Chunk 80, date=2026-05-20: rows=9949
Chunk 81, date=2026-05-20: rows=9936
Chunk 82, date=2026-05-20: rows=9957
Chunk 83, date=2026-05-20: rows=9951
Chunk 84, date=2026-05-20: rows=9953
Chunk 85, date=2026-05-20: rows=9960
Chunk 86, date=2026-05-20: rows=9961
Chunk 87, date=2026-05-20: rows=9955
Chunk 88, date=2026-05-20: rows=9955
Chunk 89, date=2026-05-20: rows=9956
Chunk 90, date=2026-05-20: rows=9940
Chunk 91, date=2026-05-20: rows=9941
Chunk 92, date=2026-05-20: rows=9938
Chunk 93, date=2026-05-20: rows=9953
Chunk 94, date=2026-05-20: rows=9946
Chunk 95, date=2026-05-20: rows=9953
Chunk 96, date=2026-05-20: rows=9953
Chunk 97, date=2026-05-20: rows=9944
Chunk 98, date=2026-05-20: rows=9949
Chunk 99, date=2026-05-20: rows=9950
Chunk 100, date=2026-05-20: rows=9940
Chunk 101, date=2026-05-20: rows=9933
Chunk 102, date=2026-05-20: rows=9930
Chunk 103, date=2026-05-20: rows=9938
Chunk 104, date=2026-05-20: rows=9936
Chunk 105, date=2026-05-20: rows=9937
Chunk 106, date=2026-05-20: rows=9943
Chunk 107, date=2026-05-20: rows=9939
Chunk 108, date=2026-05-20: rows=9938
Chunk 109, date=2026-05-20: rows=9937
Chunk 110, date=2026-05-20: rows=9929
Chunk 111, date=2026-05-20: rows=9929
Chunk 112, date=2026-05-20: rows=9916
Chunk 113, date=2026-05-20: rows=9913
Chunk 114, date=2026-05-20: rows=9919
Chunk 115, date=2026-05-20: rows=9917
Chunk 116, date=2026-05-20: rows=9937
Chunk 117, date=2026-05-20: rows=9934
Chunk 118, date=2026-05-20: rows=9919
Chunk 119, date=2026-05-20: rows=9927
Chunk 120, date=2026-05-20: rows=9912
Chunk 121, date=2026-05-20: rows=9911
Chunk 122, date=2026-05-20: rows=9903
Chunk 123, date=2026-05-20: rows=9907
Chunk 124, date=2026-05-20: rows=9902
Chunk 125, date=2026-05-20: rows=9914
Chunk 126, date=2026-05-20: rows=9918
Chunk 127, date=2026-05-20: rows=9914
Chunk 128, date=2026-05-20: rows=9911
Chunk 129, date=2026-05-20: rows=9910
Chunk 130, date=2026-05-20: rows=9896
Chunk 131, date=2026-05-20: rows=9883
Chunk 132, date=2026-05-20: rows=9887
Chunk 133, date=2026-05-20: rows=9890
Chunk 134, date=2026-05-20: rows=9885
Chunk 135, date=2026-05-20: rows=9890
Chunk 136, date=2026-05-20: rows=9904
Chunk 137, date=2026-05-20: rows=9900
Chunk 138, date=2026-05-20: rows=9902
Chunk 139, date=2026-05-20: rows=9894
Chunk 140, date=2026-05-20: rows=9880
Chunk 141, date=2026-05-20: rows=9877
Chunk 142, date=2026-05-20: rows=9877
Chunk 143, date=2026-05-20: rows=9753
Chunk 144, date=2026-05-20: rows=9584
Chunk 145, date=2026-05-20: rows=9488
Chunk 146, date=2026-05-20: rows=9481
Chunk 147, date=2026-05-20: rows=9480
Chunk 148, date=2026-05-20: rows=9457
Chunk 149, date=2026-05-20: rows=9444
Chunk 150, date=2026-05-20: rows=9416
Chunk 151, date=2026-05-20: rows=9409
Chunk 152, date=2026-05-20: rows=9406
Chunk 153, date=2026-05-20: rows=9396
Chunk 154, date=2026-05-20: rows=9381
Chunk 155, date=2026-05-20: rows=9364
Chunk 156, date=2026-05-20: rows=9380
Chunk 157, date=2026-05-20: rows=9392
Chunk 158, date=2026-05-20: rows=9412
Chunk 159, date=2026-05-20: rows=9427
Chunk 160, date=2026-05-20: rows=9410
Chunk 161, date=2026-05-20: rows=9441
Chunk 162, date=2026-05-20: rows=9423
Chunk 163, date=2026-05-20: rows=9441
Chunk 164, date=2026-05-20: rows=9439
Chunk 165, date=2026-05-20: rows=9434
Chunk 166, date=2026-05-20: rows=9428
Chunk 167, date=2026-05-20: rows=9423
Chunk 168, date=2026-05-20: rows=9449
Chunk 169, date=2026-05-20: rows=9439
Chunk 170, date=2026-05-20: rows=9425
Chunk 171, date=2026-05-20: rows=9470
Chunk 172, date=2026-05-20: rows=9450
Chunk 173, date=2026-05-20: rows=9451
Chunk 174, date=2026-05-20: rows=9461
Chunk 175, date=2026-05-20: rows=9464
Chunk 176, date=2026-05-20: rows=9441
Chunk 177, date=2026-05-20: rows=9455
Chunk 178, date=2026-05-20: rows=9446
Chunk 179, date=2026-05-20: rows=9414
Chunk 180, date=2026-05-20: rows=9406
Chunk 181, date=2026-05-20: rows=9363
Chunk 182, date=2026-05-20: rows=9355
Chunk 183, date=2026-05-20: rows=9329
Chunk 184, date=2026-05-20: rows=9327
Chunk 185, date=2026-05-20: rows=9323
Chunk 186, date=2026-05-20: rows=9318
Chunk 187, date=2026-05-20: rows=9300
Chunk 188, date=2026-05-20: rows=9323
Chunk 189, date=2026-05-20: rows=9252
Chunk 190, date=2026-05-20: rows=9254
Chunk 191, date=2026-05-20: rows=9268
Chunk 192, date=2026-05-20: rows=9324
Chunk 193, date=2026-05-20: rows=9316
Chunk 194, date=2026-05-20: rows=9333
Chunk 195, date=2026-05-20: rows=9332
Chunk 196, date=2026-05-20: rows=9330
Chunk 197, date=2026-05-20: rows=9323
Chunk 198, date=2026-05-20: rows=9328
Chunk 199, date=2026-05-20: rows=9310
Chunk 200, date=2026-05-20: rows=9284
Chunk 201, date=2026-05-20: rows=9503
Chunk 202, date=2026-05-20: rows=9739
Chunk 203, date=2026-05-20: rows=9775
Chunk 204, date=2026-05-20: rows=9793
Chunk 205, date=2026-05-20: rows=9781
Chunk 206, date=2026-05-20: rows=9807
Chunk 207, date=2026-05-20: rows=9773
Chunk 208, date=2026-05-20: rows=9793
Chunk 209, date=2026-05-20: rows=9868
Chunk 210, date=2026-05-20: rows=9931
Chunk 211, date=2026-05-20: rows=9943
Chunk 212, date=2026-05-20: rows=9932
Chunk 213, date=2026-05-20: rows=9950
Chunk 214, date=2026-05-20: rows=9947
Chunk 215, date=2026-05-20: rows=9961
Chunk 216, date=2026-05-20: rows=9950
Chunk 217, date=2026-05-20: rows=9947
Chunk 218, date=2026-05-20: rows=9954
Chunk 219, date=2026-05-20: rows=9944
Chunk 220, date=2026-05-20: rows=9943
Chunk 221, date=2026-05-20: rows=9940
Chunk 222, date=2026-05-20: rows=9948
Chunk 223, date=2026-05-20: rows=9942
Chunk 224, date=2026-05-20: rows=9958
Chunk 225, date=2026-05-20: rows=9964
Chunk 226, date=2026-05-20: rows=9953
Chunk 227, date=2026-05-20: rows=9951
Chunk 228, date=2026-05-20: rows=9955
Chunk 229, date=2026-05-20: rows=9944
Chunk 230, date=2026-05-20: rows=9944
Chunk 231, date=2026-05-20: rows=9936
Chunk 232, date=2026-05-20: rows=9946
Chunk 233, date=2026-05-20: rows=9941
Chunk 234, date=2026-05-20: rows=9954
Chunk 235, date=2026-05-20: rows=9955
Chunk 236, date=2026-05-20: rows=9952
Chunk 237, date=2026-05-20: rows=9957
Chunk 238, date=2026-05-20: rows=9939
Chunk 239, date=2026-05-20: rows=9943
Chunk 240, date=2026-05-20: rows=9945
Chunk 241, date=2026-05-20: rows=9928
Chunk 242, date=2026-05-20: rows=9949
Chunk 243, date=2026-05-20: rows=9946
Chunk 244, date=2026-05-20: rows=9962
Chunk 245, date=2026-05-20: rows=9950
Chunk 246, date=2026-05-20: rows=9951
Chunk 247, date=2026-05-20: rows=9948
Chunk 248, date=2026-05-20: rows=9938
Chunk 249, date=2026-05-20: rows=9944
Chunk 250, date=2026-05-20: rows=9943
Chunk 251, date=2026-05-20: rows=9902
Chunk 252, date=2026-05-20: rows=9880
Chunk 253, date=2026-05-20: rows=9882
Chunk 254, date=2026-05-20: rows=9899
Chunk 255, date=2026-05-20: rows=9884
Chunk 256, date=2026-05-20: rows=9890
Chunk 257, date=2026-05-20: rows=9876
Chunk 258, date=2026-05-20: rows=9868
Chunk 259, date=2026-05-20: rows=9862
Chunk 260, date=2026-05-20: rows=9858
Chunk 261, date=2026-05-20: rows=9865
Chunk 262, date=2026-05-20: rows=9866
Chunk 263, date=2026-05-20: rows=9877
Chunk 264, date=2026-05-20: rows=9886
Chunk 265, date=2026-05-20: rows=9870
Chunk 266, date=2026-05-20: rows=9882
Chunk 267, date=2026-05-20: rows=9865
Chunk 268, date=2026-05-20: rows=9875
Chunk 269, date=2026-05-20: rows=9856
Chunk 270, date=2026-05-20: rows=9872
Chunk 271, date=2026-05-20: rows=9856
Chunk 272, date=2026-05-20: rows=9890
Chunk 273, date=2026-05-20: rows=9931
Chunk 274, date=2026-05-20: rows=9951
Chunk 275, date=2026-05-20: rows=9953
Chunk 276, date=2026-05-20: rows=9953
Chunk 277, date=2026-05-20: rows=9942
Chunk 278, date=2026-05-20: rows=9945
Chunk 279, date=2026-05-20: rows=9937
Chunk 280, date=2026-05-20: rows=9952
Chunk 281, date=2026-05-20: rows=9939
Chunk 282, date=2026-05-20: rows=9959
Chunk 283, date=2026-05-20: rows=9961
Chunk 284, date=2026-05-20: rows=9952
Chunk 285, date=2026-05-20: rows=9952
Chunk 286, date=2026-05-20: rows=9935
Chunk 287, date=2026-05-20: rows=9943
Chunk 288, date=2026-05-20: rows=9949
Chunk 289, date=2026-05-20: rows=9940
Chunk 290, date=2026-05-20: rows=9953
Chunk 291, date=2026-05-20: rows=9948
Chunk 292, date=2026-05-20: rows=9966
Chunk 293, date=2026-05-20: rows=9957
Chunk 294, date=2026-05-20: rows=9956
Chunk 295, date=2026-05-20: rows=9952
Chunk 296, date=2026-05-20: rows=9942
Chunk 297, date=2026-05-20: rows=9944
Chunk 298, date=2026-05-20: rows=9940
Chunk 299, date=2026-05-20: rows=9952
Chunk 300, date=2026-05-20: rows=9944
Chunk 301, date=2026-05-20: rows=9961
Chunk 302, date=2026-05-20: rows=9955
Chunk 303, date=2026-05-20: rows=9957
Chunk 304, date=2026-05-20: rows=9947
Chunk 305, date=2026-05-20: rows=9934
Chunk 306, date=2026-05-20: rows=9950
Chunk 307, date=2026-05-20: rows=9942
Chunk 308, date=2026-05-20: rows=9946
Chunk 309, date=2026-05-20: rows=9948
Chunk 310, date=2026-05-20: rows=9960
Chunk 311, date=2026-05-20: rows=9964
Chunk 312, date=2026-05-20: rows=9958
Chunk 313, date=2026-05-20: rows=9958
Chunk 314, date=2026-05-20: rows=9951
Chunk 315, date=2026-05-20: rows=9943
Chunk 316, date=2026-05-20: rows=9913
Chunk 317, date=2026-05-20: rows=9872
Chunk 318, date=2026-05-20: rows=9870
Chunk 319, date=2026-05-20: rows=9866
Chunk 320, date=2026-05-20: rows=9878
Chunk 321, date=2026-05-20: rows=9868
Chunk 322, date=2026-05-20: rows=9875
Chunk 323, date=2026-05-20: rows=9888
Chunk 324, date=2026-05-20: rows=9857
Chunk 325, date=2026-05-20: rows=9878
Chunk 326, date=2026-05-20: rows=9862
Chunk 327, date=2026-05-20: rows=9864
Chunk 328, date=2026-05-20: rows=9869
Chunk 329, date=2026-05-20: rows=9863
Chunk 330, date=2026-05-20: rows=9875
Chunk 331, date=2026-05-20: rows=9864
Chunk 332, date=2026-05-20: rows=9889
Chunk 333, date=2026-05-20: rows=9860
Chunk 334, date=2026-05-20: rows=9882
Chunk 335, date=2026-05-20: rows=9873
Chunk 336, date=2026-05-20: rows=9857
Chunk 337, date=2026-05-20: rows=9872
Chunk 338, date=2026-05-20: rows=9869
Chunk 339, date=2026-05-20: rows=9878
Chunk 340, date=2026-05-20: rows=9856
Chunk 341, date=2026-05-20: rows=9898
Chunk 342, date=2026-05-20: rows=9871
Chunk 343, date=2026-05-20: rows=9872
Chunk 344, date=2026-05-20: rows=9865
Chunk 345, date=2026-05-20: rows=9847
Chunk 346, date=2026-05-20: rows=9873
Chunk 347, date=2026-05-20: rows=9857
Chunk 348, date=2026-05-20: rows=9877
Chunk 349, date=2026-05-20: rows=9855
Chunk 350, date=2026-05-20: rows=9892
Chunk 351, date=2026-05-20: rows=9872
Chunk 352, date=2026-05-20: rows=9873
Chunk 353, date=2026-05-20: rows=9870
Chunk 354, date=2026-05-20: rows=9846
Chunk 355, date=2026-05-20: rows=9882
Chunk 356, date=2026-05-20: rows=9869
Chunk 357, date=2026-05-20: rows=9878
Chunk 358, date=2026-05-20: rows=9863
Chunk 359, date=2026-05-20: rows=9891
Chunk 360, date=2026-05-20: rows=9901
Chunk 361, date=2026-05-20: rows=9871
Chunk 362, date=2026-05-20: rows=9877
Chunk 363, date=2026-05-20: rows=9882
Chunk 364, date=2026-05-20: rows=9875
Chunk 365, date=2026-05-20: rows=9884
Chunk 366, date=2026-05-20: rows=9874
Chunk 367, date=2026-05-20: rows=9888
Chunk 368, date=2026-05-20: rows=9869
Chunk 369, date=2026-05-20: rows=9883
Chunk 370, date=2026-05-20: rows=9897
Chunk 371, date=2026-05-20: rows=9866
Chunk 372, date=2026-05-20: rows=9862
Chunk 373, date=2026-05-20: rows=9858
Chunk 374, date=2026-05-20: rows=9869
Chunk 375, date=2026-05-20: rows=9870
Chunk 376, date=2026-05-20: rows=9871
Chunk 377, date=2026-05-20: rows=9868
Chunk 378, date=2026-05-20: rows=9871
Chunk 379, date=2026-05-20: rows=9889
Chunk 380, date=2026-05-20: rows=9862
Chunk 381, date=2026-05-20: rows=9870
Chunk 382, date=2026-05-20: rows=9862
Chunk 383, date=2026-05-20: rows=9863
Chunk 384, date=2026-05-20: rows=9868
Chunk 385, date=2026-05-20: rows=9869
Chunk 386, date=2026-05-20: rows=9855
Chunk 387, date=2026-05-20: rows=9860
Chunk 388, date=2026-05-20: rows=9886
Chunk 389, date=2026-05-20: rows=9858
Chunk 390, date=2026-05-20: rows=9861
Chunk 391, date=2026-05-20: rows=9868
Chunk 392, date=2026-05-20: rows=9867
Chunk 393, date=2026-05-20: rows=9872
Chunk 394, date=2026-05-20: rows=9880
Chunk 395, date=2026-05-20: rows=9865
Chunk 396, date=2026-05-20: rows=9868
Chunk 397, date=2026-05-20: rows=9887
Chunk 398, date=2026-05-20: rows=9864
Chunk 399, date=2026-05-20: rows=9874
Chunk 400, date=2026-05-20: rows=9859
Chunk 401, date=2026-05-20: rows=9861
Chunk 402, date=2026-05-20: rows=9864
Chunk 403, date=2026-05-20: rows=9870
Chunk 404, date=2026-05-20: rows=9859
Chunk 405, date=2026-05-20: rows=9864
Chunk 406, date=2026-05-20: rows=9889
Chunk 407, date=2026-05-20: rows=9859
Chunk 408, date=2026-05-20: rows=9871
Chunk 409, date=2026-05-20: rows=9872
Chunk 410, date=2026-05-20: rows=9856
Chunk 411, date=2026-05-20: rows=9872
Chunk 412, date=2026-05-20: rows=9871
Chunk 413, date=2026-05-20: rows=9858
Chunk 414, date=2026-05-20: rows=9867
Chunk 415, date=2026-05-20: rows=9890
Chunk 416, date=2026-05-20: rows=9865
Chunk 417, date=2026-05-20: rows=9887
Chunk 418, date=2026-05-20: rows=9877
Chunk 419, date=2026-05-20: rows=9866
Chunk 420, date=2026-05-20: rows=9886
Chunk 421, date=2026-05-20: rows=9871
Chunk 422, date=2026-05-20: rows=9877
Chunk 423, date=2026-05-20: rows=9860
Chunk 424, date=2026-05-20: rows=9880
Chunk 425, date=2026-05-20: rows=9892
Chunk 426, date=2026-05-20: rows=9861
Chunk 427, date=2026-05-20: rows=9868
Chunk 428, date=2026-05-20: rows=9843
Chunk 429, date=2026-05-20: rows=9875
Chunk 430, date=2026-05-20: rows=9861
Chunk 431, date=2026-05-20: rows=9871
Chunk 432, date=2026-05-20: rows=9849
Chunk 433, date=2026-05-20: rows=9877
Chunk 434, date=2026-05-20: rows=9879
Chunk 435, date=2026-05-20: rows=9869
Chunk 436, date=2026-05-20: rows=9864
Chunk 437, date=2026-05-20: rows=9846
Chunk 438, date=2026-05-20: rows=9873
Chunk 439, date=2026-05-20: rows=9858
Chunk 440, date=2026-05-20: rows=9881
Chunk 441, date=2026-05-20: rows=9854
Chunk 442, date=2026-05-20: rows=9881
Chunk 443, date=2026-05-20: rows=9870
Chunk 444, date=2026-05-20: rows=9879
Chunk 445, date=2026-05-20: rows=9872
Chunk 446, date=2026-05-20: rows=9854
Chunk 447, date=2026-05-20: rows=9890
Chunk 448, date=2026-05-20: rows=9875
Chunk 449, date=2026-05-20: rows=9897
Chunk 450, date=2026-05-20: rows=9865
Chunk 451, date=2026-05-20: rows=9872
Chunk 452, date=2026-05-20: rows=9895
Chunk 453, date=2026-05-20: rows=9868
Chunk 454, date=2026-05-20: rows=9882
Chunk 455, date=2026-05-20: rows=9866
Chunk 456, date=2026-05-20: rows=9854
Chunk 457, date=2026-05-20: rows=9862
Chunk 458, date=2026-05-20: rows=9874
Chunk 459, date=2026-05-20: rows=9881
Chunk 460, date=2026-05-20: rows=9853
Chunk 461, date=2026-05-20: rows=9879
Chunk 462, date=2026-05-20: rows=9868
Chunk 463, date=2026-05-20: rows=9881
Chunk 464, date=2026-05-20: rows=9859
Chunk 465, date=2026-05-20: rows=9858
Chunk 466, date=2026-05-20: rows=9864
Chunk 467, date=2026-05-20: rows=9863
Chunk 468, date=2026-05-20: rows=9881
Chunk 469, date=2026-05-20: rows=9856
Chunk 470, date=2026-05-20: rows=9881
Chunk 471, date=2026-05-20: rows=9868
Chunk 472, date=2026-05-20: rows=9879
Chunk 473, date=2026-05-20: rows=9867
Chunk 474, date=2026-05-20: rows=9865
Chunk 475, date=2026-05-20: rows=9893
Chunk 476, date=2026-05-20: rows=9876
Chunk 477, date=2026-05-20: rows=9886
Chunk 478, date=2026-05-20: rows=9879
Chunk 479, date=2026-05-20: rows=9874
Chunk 480, date=2026-05-20: rows=9899
Chunk 481, date=2026-05-20: rows=9871
Chunk 482, date=2026-05-20: rows=9877
Chunk 483, date=2026-05-20: rows=9861
Chunk 484, date=2026-05-20: rows=9865
Chunk 485, date=2026-05-20: rows=9868
Chunk 486, date=2026-05-20: rows=9867
Chunk 487, date=2026-05-20: rows=9870
Chunk 488, date=2026-05-20: rows=9859
Chunk 489, date=2026-05-20: rows=9877
Chunk 490, date=2026-05-20: rows=9866
Chunk 491, date=2026-05-20: rows=9870
Chunk 492, date=2026-05-20: rows=9857
Chunk 493, date=2026-05-20: rows=9861
Chunk 494, date=2026-05-20: rows=9870
Chunk 495, date=2026-05-20: rows=9869
Chunk 496, date=2026-05-20: rows=9881
Chunk 497, date=2026-05-20: rows=9861
Chunk 498, date=2026-05-20: rows=9880
Chunk 499, date=2026-05-20: rows=9862
Chunk 500, date=2026-05-20: rows=9871
Chunk 501, date=2026-05-20: rows=9872
Chunk 502, date=2026-05-20: rows=9855
Chunk 503, date=2026-05-20: rows=9879
Chunk 504, date=2026-05-20: rows=9874
Chunk 505, date=2026-05-20: rows=9885
Chunk 506, date=2026-05-20: rows=9866
Chunk 507, date=2026-05-20: rows=9878
Chunk 508, date=2026-05-20: rows=9881
Chunk 509, date=2026-05-20: rows=9868
Chunk 510, date=2026-05-20: rows=9862
Chunk 511, date=2026-05-20: rows=9846
Chunk 512, date=2026-05-20: rows=9871
Chunk 513, date=2026-05-20: rows=9863
Chunk 514, date=2026-05-20: rows=9878
Chunk 515, date=2026-05-20: rows=9854
Chunk 516, date=2026-05-20: rows=9869
Chunk 517, date=2026-05-20: rows=9884
Chunk 518, date=2026-05-20: rows=9862
Chunk 519, date=2026-05-20: rows=9862
Chunk 520, date=2026-05-20: rows=9843
Chunk 521, date=2026-05-20: rows=9878
Chunk 522, date=2026-05-20: rows=9856
Chunk 523, date=2026-05-20: rows=9874
Chunk 524, date=2026-05-20: rows=9853
Chunk 525, date=2026-05-20: rows=9874
Chunk 526, date=2026-05-20: rows=9872
Chunk 527, date=2026-05-20: rows=9867
Chunk 528, date=2026-05-20: rows=9877

In [42]:
df = pd.read_parquet(r"C:\Users\radet\Praksa\automatisation\output\iptv_2026-04-21.parquet")

In [44]:
df_m = df[(df["type"] == "RESTARTUsage") & (df["name"] == "Divlje p─ìele")]
df_m

,devRef,name,type,duration,extra,insertedTS,timeZone
268,9294460022083742,Divlje p─ìele,RESTARTUsage,300052,"{""title"":""Divlje p─ìele"",""genre"":""Film"",""start...",2026-04-21 00:00:00,UTC+02:00
921,9905460028863251,Divlje p─ìele,RESTARTUsage,263164,"{""title"":""Divlje p─ìele"",""genre"":""Film"",""start...",2026-04-21 00:00:00,UTC+01:00
1653,9881740028396502,Divlje p─ìele,RESTARTUsage,300060,"{""title"":""Divlje p─ìele"",""genre"":""Film"",""start...",2026-04-21 00:00:07,UTC+01:00
5045,2317940024581191,Divlje p─ìele,RESTARTUsage,300069,"{""title"":""Divlje p─ìele"",""genre"":""Film"",""start...",2026-04-21 00:00:26,UTC+01:00
5876,3259170026849221,Divlje p─ìele,RESTARTUsage,300152,"{""title"":""Divlje p─ìele"",""genre"":""Film"",""start...",2026-04-21 00:00:26,UTC+02:00
...,...,...,...,...,...,...,...
13405130,2317940024581191,Divlje p─ìele,RESTARTUsage,300124,"{""title"":""Divlje p─ìele"",""genre"":""Film"",""start...",2026-04-21 23:59:28,UTC+01:00
13405441,4757870011694802,Divlje p─ìele,RESTARTUsage,300037,"{""title"":""Divlje p─ìele"",""genre"":""Film"",""start...",2026-04-21 23:59:38,UTC+02:00
13407950,59835200098426700001,Divlje p─ìele,RESTARTUsage,300067,"{""title"":""Divlje p─ìele"",""genre"":""Film"",""start...",2026-04-21 23:59:51,UTC+02:00
13408332,5031300025507981,Divlje p─ìele,RESTARTUsage,300059,"{""title"":""Divlje p─ìele"",""genre"":""Film"",""start...",2026-04-21 23:59:54,UTC+02:00
13408893,9231850026016141,Divlje p─ìele,RESTARTUsage,300070,"{""title"":""Divlje p─ìele"",""genre"":""Film"",""start...",2026-04-21 23:59:54,UTC+02:00

In [7]:
df = load_event_data("RESTARTUsage")

In [8]:
df

,devRef,name,duration,extra,insertedTS,timeZone
0,3276800023118281,Divlje pčele,300017,"{""title"":""Divlje pčele"",""genre"":""Film"",""startT...",2026-05-20 00:00:00,UTC+02:00
1,77083000317985700001,Divlje pčele,300053,"{""title"":""Divlje pčele"",""genre"":""Film"",""startT...",2026-05-20 00:00:00,UTC+02:00
2,702700014128941,Divlje pčele,300046,"{""title"":""Divlje pčele"",""genre"":""Film"",""startT...",2026-05-20 00:00:06,UTC+02:00
3,9450000193616600001,Divlje pčele,300050,"{""title"":""Divlje pčele"",""genre"":""Film"",""startT...",2026-05-20 00:00:09,UTC+02:00
4,5291990029961411,Divlje pčele,300075,"{""title"":""Divlje pčele"",""genre"":""Film"",""startT...",2026-05-20 00:00:09,UTC+02:00
...,...,...,...,...,...,...
17283,2921160032869341,Divlje pčele,300038,"{""title"":""Divlje pčele"",""genre"":""Film"",""startT...",2026-05-20 23:59:50,UTC+02:00
17284,10038160030369902,Divlje pčele,300068,"{""title"":""Divlje pčele"",""genre"":""Film"",""startT...",2026-05-20 23:59:51,UTC+02:00
17285,10024510030143041,Divlje pčele,300183,"{""title"":""Divlje pčele"",""genre"":""Film"",""startT...",2026-05-20 23:59:51,UTC+02:00
17286,1328420019076531,Divlje pčele,300059,"{""title"":""Divlje pčele"",""genre"":""Film"",""startT...",2026-05-20 23:59:56,UTC+02:00
17287,9935180029063462,Divlje pčele,300085,"{""title"":""Divlje pčele"",""genre"":""Film"",""startT...",2026-05-20 23:59:56,UTC+02:00