In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [2]:
def build_sessions(
    df: pd.DataFrame,
    max_gap_ms: int = 400000,
    heartbeat_ms : int = 300000,
) -> pd.DataFrame:

    group_cols = ["devRef", "name", "extra"]

    df = df.copy()
    df["insertedTS"] = pd.to_datetime(df["insertedTS"])
    df["event_start_ts"] = (
        df["insertedTS"]
        + pd.to_timedelta(
            heartbeat_ms - df["duration"],
            unit="ms",
    )
)
    df["event_end_ts"] = df["insertedTS"] + pd.to_timedelta(
        df["duration"],
        unit="ms",
    )

    df = df.sort_values(group_cols + ["event_start_ts"])

    df["prev_end_ts"] = df.groupby(group_cols)["event_end_ts"].shift()

    df["gap"] = (
        df["event_start_ts"] - df["prev_end_ts"]
    ).dt.total_seconds() * 1000

    df["new_session"] = (
        df["gap"].isna()
        | (df["gap"] > max_gap_ms)
    )

    df["session_id"] = df.groupby(group_cols)["new_session"].cumsum()

    sessions = (
        df.groupby(group_cols + ["session_id"], as_index=False, observed=True)
        .agg(
            start_ts=("event_start_ts", "min"),
            end_ts=("event_end_ts", "max"),
            timezone=("timeZone", "first"),
            event_count=("insertedTS", "count"),
            duration=("duration", "sum"),
        )
    )
    
    invalid_mask = (
        sessions["end_ts"]
        < sessions["start_ts"]
    )

    sessions.loc[
        invalid_mask,
        "end_ts"
    ] = (
        sessions.loc[
            invalid_mask,
            "start_ts"
        ]
        + pd.to_timedelta(
            sessions.loc[
                invalid_mask,
                "duration"
            ],
            unit="ms",
        )
    )
    
    sessions["total_duration"] = (
        sessions["end_ts"] - sessions["start_ts"]
    ).dt.total_seconds() * 1000

    sessions["start_ts"] = (
        sessions["start_ts"]
        .dt.floor("s")
    )

    sessions["end_ts"] = (
        sessions["end_ts"]
        .dt.floor("s")
    )
    
    return sessions.drop(columns=["session_id"])

In [74]:
import orjson

def extract_columns_from_extra(
    df: pd.DataFrame,
    column: str,
    keys: list[str],
    drop_source: bool = True,
) -> pd.DataFrame:

    parsed = df[column].map(
        lambda x: orjson.loads(x) if x else {}  # type: ignore
    )

    for key in keys:
        df[key] = parsed.str.get(key)

        if df[key].dtype == "object":
            df[key] = df[key].astype("category")

    if drop_source:
        df.drop(columns=[column], inplace=True)

    del parsed

    return df

In [104]:
INVALID_VALUES = {
    None,
    "",
    "other",
    "null",
    "no title",
    "0",
    "-1",
}

REQUIRED_KEYS = (
    "title",
    "genre",
    "startTime",
    "programId",
    "duration",
)


def has_invalid_extra(x):

    data = orjson.loads(x)

    for key in REQUIRED_KEYS:
        val = data.get(key)

        if isinstance(val, str):
            val = val.strip().lower()

        if val in INVALID_VALUES:
            return True

    return False

In [116]:
def build_iptv_sessions(
    df: pd.DataFrame,
    max_gap_ms: int = 400000,
    heartbeat_ms: int = 300000,
) -> pd.DataFrame:
    df_sessions = build_sessions(
        df,
        max_gap_ms=max_gap_ms,
        heartbeat_ms=heartbeat_ms,
    )

    df_sessions = extract_columns_from_extra(
        df_sessions,
        "extra",
        ["title", "genre", "startTime", "programId", "duration", "location"],
    )
    
    df_sessions = df_sessions[df_sessions["duration"] > 0]

    df_sessions["program_start"] = pd.to_datetime(
        df_sessions["startTime"],
        unit="ms",
        utc=True,
    )

    df_sessions.drop(columns=["startTime"], inplace=True)

    df_sessions["offset_hours"] = (
        df_sessions["timezone"].str.extract(r"([+-]\d{2})", expand=False).astype(int)
    )

    df_sessions["program_start_local"] = df_sessions["program_start"].dt.tz_localize(
        None
    ) + pd.to_timedelta(df_sessions["offset_hours"], unit="h")

    df_sessions.drop(
        columns=["timezone", "program_start", "offset_hours"],
        inplace=True,
    )

    columns = [
        "devRef",
        "name",
        "title",
        "genre",
        "programId",
        "location",
        "program_start_local",
        "start_ts",
        "end_ts",
        "duration",
        "total_duration",
    ]

    result: pd.DataFrame = pd.DataFrame(df_sessions.loc[:, columns]).copy()

    return result

In [5]:
db_uri = "mysql+pymysql://statsuser:statspass@localhost:3306/statsdb"
engine = create_engine(db_uri)

In [6]:
query = """
SELECT *
FROM statistic
WHERE type = 'LiveUsage';
"""

In [7]:
df = pd.read_sql(query, engine)

In [92]:
df = df[df["duration"] <= 400000]
mask = df["extra"].map(has_invalid_extra)
df = df.loc[~mask]

In [93]:
df_original = df.copy()

In [117]:
df_sessions= build_iptv_sessions(df)

In [118]:
df_sessions_original = df_sessions.copy()

In [135]:
df_sessions

,devRef,name,title,genre,programId,location,program_start_local,start_ts,end_ts,duration,total_duration
0,3386180021773581,Arena Premium 1 HD,Fudbal - WWin Liga BiH,Sport,68524023,TREBINJE,2026-04-20 23:30:00,2026-04-21 00:03:06,2026-04-21 01:35:08,7200000,5521076.0
1,3386180021773581,Arena Premium 1 HD,Fudbal - WWin Liga BiH,Sport,68524029,TREBINJE,2026-04-21 06:00:00,2026-04-21 06:05:07,2026-04-21 08:08:16,7200000,7388087.0
2,3386180021773581,Arena Premium 1 HD,Fudbal - WWin Liga BiH,Sport,68524030,TREBINJE,2026-04-21 08:00:00,2026-04-21 08:08:05,2026-04-21 10:08:13,7200000,7207116.0
3,3386180021773581,Arena Premium 1 HD,Fudbal - WWin Liga BiH,Sport,68524031,TREBINJE,2026-04-21 10:00:00,2026-04-21 10:08:13,2026-04-21 12:08:11,7200000,7197128.0
4,3386180021773581,Arena Premium 1 HD,Fudbal - WWin Liga BiH,Sport,68524032,TREBINJE,2026-04-21 12:00:00,2026-04-21 12:08:15,2026-04-21 14:04:11,7200000,6955074.0
...,...,...,...,...,...,...,...,...,...,...,...
2451923,f27376890a6ff34c2b7d09f3798c7e23,Baby TV,Welcome to the Island,Ostalo,68446317,Banjaluka,2026-04-21 07:19:00,2026-04-21 07:23:56,2026-04-21 07:24:57,360000,60001.0
2451924,f27376890a6ff34c2b7d09f3798c7e23,Baby TV,Welcome to the Island,Ostalo,68446451,Banjaluka,2026-04-21 17:11:00,2026-04-21 17:15:39,2026-04-21 17:20:40,300000,300046.0
2451925,f27376890a6ff34c2b7d09f3798c7e23,Baby TV,What a Wonderful Day,Ostalo,68446453,Banjaluka,2026-04-21 17:21:00,2026-04-21 17:28:39,2026-04-21 17:29:40,180000,60010.0
2451926,f27376890a6ff34c2b7d09f3798c7e23,Baby TV,Zeina's Detective Agency,Ostalo,68446316,Banjaluka,2026-04-21 07:14:00,2026-04-21 07:19:15,2026-04-21 07:22:57,300000,221018.0
2451927,f27376890a6ff34c2b7d09f3798c7e23,Baby TV,Zeina's Detective Agency,Ostalo,68446464,Banjaluka,2026-04-21 18:01:00,2026-04-21 18:05:31,2026-04-21 18:12:40,420000,428018.0

In [136]:
def compute_watch_ranges(df: pd.DataFrame) -> pd.DataFrame:

    # zaštita
    df = df.copy()

    # numeric
    df["total_duration"] = pd.to_numeric(
        df["total_duration"],
        errors="coerce",
    )

    df["duration"] = pd.to_numeric(
        df["duration"],
        errors="coerce",
    )

    # procenat odgledanog
    df["watch_ratio"] = df["total_duration"] / df["duration"]

    # kategorije
    conditions = [
        (df["watch_ratio"] >= 0.75),
        (df["watch_ratio"] >= 0.50) & (df["watch_ratio"] < 0.75),
        (df["watch_ratio"] >= 0.25) & (df["watch_ratio"] < 0.50),
        (df["watch_ratio"] < 0.25),
    ]

    choices = [
        "75-100%",
        "50-75%",
        "25-50%",
        "0-25%"
    ]

    df["watch_group"] = pd.Series(
        pd.NA,
        index=df.index,
        dtype="object",
    )

    for cond, value in zip(conditions, choices):
        df.loc[cond, "watch_group"] = value

    # izbaci sve ispod 25%
    df = df[df["watch_group"].notna()]

    # grupisanje
    result = (
        df.groupby(
            ["name", "title", "programId", "watch_group"],
            observed=True,
        )["devRef"]
        .nunique()
        .reset_index(name="viewer_count")
    )

    # pivot da bude preglednije
    result = result.pivot_table(
        index=["name", "title", "programId"],
        columns="watch_group",
        values="viewer_count",
        fill_value=0,
    ).reset_index()
    
    result = result.sort_values(
    by=["75-100%", "50-75%", "25-50%", "0-25%"],
    ascending=False,
    )

    return result

In [147]:
def comp_watch_ranges(
    df: pd.DataFrame,
) -> pd.DataFrame:

    df["total_duration"] = pd.to_numeric(
        df["total_duration"],
        errors="coerce",
    )

    df["duration"] = pd.to_numeric(
        df["duration"],
        errors="coerce",
    )

    df = df[df["duration"] > 0]

    df["watch_ratio"] = (
        df["total_duration"]
        / df["duration"]
    )

    conditions = [
        (df["watch_ratio"] >= 0.75),

        (
            (df["watch_ratio"] >= 0.50)
            & (df["watch_ratio"] < 0.75)
        ),

        (
            (df["watch_ratio"] >= 0.25)
            & (df["watch_ratio"] < 0.50)
        ),

        (df["watch_ratio"] < 0.25),
    ]

    choices = [
        "75-100%",
        "50-75%",
        "25-50%",
        "0-25%",
    ]

    df["watch_group"] = pd.NA

    for cond, value in zip(
        conditions,
        choices,
    ):
        df.loc[
            cond,
            "watch_group",
        ] = value

    grouped = (
        df.groupby(
            [
                "name",
                "title",
                "programId",
                "watch_group",
            ],
            observed=True,
        )["devRef"]
        .nunique()
        .unstack(fill_value=0)
        .reset_index()
    )

    # osiguraj da sve kolone postoje
    for col in choices:
        if col not in grouped.columns:
            grouped[col] = 0

    result = grouped[
        [
            "name",
            "title",
            "programId",
            "75-100%",
            "50-75%",
            "25-50%",
            "0-25%",
        ]
    ]

    result = result.sort_values(
        by=[
            "75-100%",
            "50-75%",
            "25-50%",
            "0-25%",
        ],
        ascending=False,
    )

    return result

In [148]:
ranges = comp_watch_ranges(df_sessions)

In [149]:
ranges

watch_group,name,title,programId,75-100%,50-75%,25-50%,0-25%
1681,BN HD,Dnevnik 2,68462975,8532,1502,1379,3349
1680,BN HD,Dnevnik 1,68462970,5880,964,604,922
1707,BN HD,Zarobljena,68462976,5730,665,848,5034
11763,RTRS,Dnevnik 2,68586920,4984,1796,1219,3415
1679,BN HD,Danas u Srpskoj,68462973,4356,672,679,1390
...,...,...,...,...,...,...,...
15469,Yachting TV HD,Walkthrough by Denison,68526865,0,0,0,1
15471,Yachting TV HD,Walkthrough by Denison,68526873,0,0,0,1
15472,Yachting TV HD,Walkthrough by Denison,68526882,0,0,0,1
15476,Yachting TV HD,Walkthrough by Denison,68526891,0,0,0,1
15488,Zelena TV Zdravlje,Bolje sprečiti,68426484,0,0,0,1

In [139]:
def sum_sessions(df: pd.DataFrame, extra=None) -> pd.DataFrame:
    group_cols = ["devRef", "name"]

    if extra:
        if isinstance(extra, list):
            group_cols.extend(extra)
        else:
            group_cols.append(extra)

    return df.groupby(
        group_cols,
        as_index=False,
        observed=True,
    ).agg(duration=("total_duration", "sum"))

In [140]:
def count_name_occurrences(
    df: pd.DataFrame,
    min_duration: int = 30000,
    group_cols: str | list[str] = "name",
) -> pd.DataFrame:

    df = sum_sessions(df)

    if df.empty:
        return pd.DataFrame()

    if "duration" not in df.columns:
        raise ValueError("Column 'duration' does not exist in DataFrame")

    # osiguraj da je lista
    if isinstance(group_cols, str):
        group_cols = [group_cols]

    # provjera da kolone postoje
    missing = [col for col in group_cols if col not in df.columns]
    if missing:
        raise ValueError(f"Columns not found: {missing}")

    filtered = df[(df["duration"].isna()) | (df["duration"] >= min_duration)]

    return (
        filtered.groupby(
            group_cols,
            as_index=False,
            observed=True,
        )
        .size()
        .rename(columns={"size": "count"})  # type: ignore
        .sort_values(by="count", ascending=False)
    )

In [141]:
sumirano = sum_sessions(df_sessions)
sumirano = sumirano.sort_values(
            by="duration",
            ascending=False,
            ignore_index=True,
        )
sumirano

                      devRef           name    duration
0           3005110027556171     Cartoonito  86776620.0
1          10034510032186813          BN HD  86721853.0
2           8826500031736611           RTRS  86704878.0
3          99991904714899993      NickToons  86693909.0
4            810460009516411           RTRS  86604467.0
...                      ...            ...         ...
688899  93851000227814200001  Arena Sport 2        34.0
688900      9813470027294772           RTRS        31.0
688901      1085840025617661       TV K3 HD        28.0
688902      8591100013384621           RTRS        16.0
688903       989020025248111        DocuBox         6.0

[688904 rows x 3 columns]

In [142]:
count = count_name_occurrences(df_sessions)
count

                 name  count
62              BN HD  26941
345              RTRS  24873
4              ATV HD  16190
328              Prva  15362
347             RTS 1  14130
..                ...    ...
415            TDC HD      1
50   ArtHouse Filmbox      1
290       Pink Folk 1      1
122         EroXXX HD      1
169      Gametoon HD       1

[460 rows x 2 columns]