In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [2]:
db_uri = "mysql+pymysql://statsuser:statspass@localhost:3306/statsdb"
engine = create_engine(db_uri)

In [3]:
query = """
SELECT *
FROM statistic
WHERE type = 'VodUsageMOVIE';
"""

In [4]:
df = pd.read_sql(query, engine)

In [5]:
df.drop_duplicates()

,id,cusRef,devRef,devType,devModel,timeZone,cusGrRefs,ref,type,name,time,duration,extra,deliveredTS,insertedTS
0,50582124472,910506002597506,91050600259750600001,MOTOROLA_4,VIP1113,UTC+02:00,"[""100131"",""1006"",""C1"",""0"",""V0"",""R1""]",6b0e724647330c0a651b66e5957bfe1c,VodUsageMOVIE,"From IV, ep. 01",1776722350506,300056,"{""shopRef"":""FOKUSON_SHOP_3"",""shopName"":""HBO OD...",1776722391605,2026-04-21 00:00:00
1,50582125752,938063002269012,9380630022690121,MOTOROLA_4,VIP1113,UTC+01:00,"[""100128"",""1006"",""C1"",""0"",""V0"",""R1""]",0d3a218696bda4e0312958d8cac06372,VodUsageMOVIE,Ta luda ljubav,1776722358382,300050,"{""shopRef"":""FOKUSON_SHOP_18"",""shopName"":""APOLL...",1776722401215,2026-04-21 00:00:07
2,50582128806,897741001770528,8977410017705281,MOTOROLA_4,VIP1113,UTC+02:00,"[""100131"",""1006"",""C1"",""0"",""10010"",""V0"",""R1""]",867987f35baf887fd1e6253e6a8973ae,VodUsageMOVIE,"Euforija III, ep. 01",1776722379527,300040,"{""shopRef"":""FOKUSON_SHOP_3"",""shopName"":""HBO OD...",1776722415181,2026-04-21 00:00:20
3,50582134742,302464001826812,3024640018268121,MOTOROLA_4,VIP1113,UTC+01:00,"[""R1"",""1006"",""C1"",""0"",""V0""]",57254f5072a22022b0b158d273a64bd7,VodUsageMOVIE,Prizivanje zla 2,1776722410571,300053,"{""shopRef"":""FOKUSON_SHOP_18"",""shopName"":""APOLL...",1776722443303,2026-04-21 00:00:49
4,50582135506,988492002850585,9884920028505851,MOTOROLA_4,VIP1113,UTC+02:00,"[""1006"",""C1"",""0"",""V0"",""R1""]",6b0e724647330c0a651b66e5957bfe1c,VodUsageMOVIE,"From IV, ep. 01",1776722416912,300045,"{""shopRef"":""FOKUSON_SHOP_3"",""shopName"":""HBO OD...",1776722447090,2026-04-21 00:00:55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5669,50595717379,984880002803529,9848800028035291,MOTOROLA_4,VIP1113,UTC+02:00,"[""1006"",""C1"",""0"",""V0"",""R1""]",bbf40d07df38a08fd9ec778924e26597,VodUsageMOVIE,Poslednji skaut,1776808728493,300054,"{""shopRef"":""FOKUSON_SHOP_18"",""shopName"":""APOLL...",1776808761481,2026-04-21 23:59:28
5670,50595718774,864666002106879,8646660021068792,MOTOROLA_4,VIP1113,UTC+02:00,"[""100128"",""1006"",""C1"",""0"",""V0"",""R1""]",3157ed1fa866977ea14379b23301aa88,VodUsageMOVIE,Internat S06E07,1776808748460,300041,"{""shopRef"":""FOKUSON_SHOP_18"",""shopName"":""APOLL...",1776808775753,2026-04-21 23:59:38
5671,50595718980,523772002412916,5237720024129162,MOTOROLA_4,VIP1113,UTC+01:00,"[""R1"",""1006"",""C1"",""0"",""V0""]",6790cfd749b167ec8f688edcd2c18942,VodUsageMOVIE,"Euforija III, ep. 02",1776808737736,60023,"{""shopRef"":""FOKUSON_SHOP_3"",""shopName"":""HBO OD...",1776808769163,2026-04-21 23:59:42
5672,50595720325,938756002275877,9387560022758771,MOTOROLA_4,VIP1113,UTC+01:00,"[""100131"",""1006"",""C1"",""0"",""V0"",""R1""]",e90262131d63606645006b0b8ece2e9c,VodUsageMOVIE,Mali zeleni,1776808751887,300044,"{""shopRef"":""FOKUSON_SHOP_3"",""shopName"":""HBO OD...",1776808783463,2026-04-21 23:59:51
5673,50595721315,949882002354254,9498820023542541,MOTOROLA_4,VIP1113,UTC+02:00,"[""100131"",""1006"",""C1"",""0"",""V0"",""R1""]",28481342084fe4f79978f6cb5790eb96,VodUsageMOVIE,Samarićanin,1776808779543,240044,"{""shopRef"":""FOKUSON_SHOP_3"",""shopName"":""HBO OD...",1776808786756,2026-04-21 23:59:54

In [6]:
import sys
import os

project_root = os.path.abspath(os.path.join(os.getcwd(), "..", ".."))
sys.path.append(project_root)

from processors.vod_usage_movie import process

In [7]:
timeshift = process(df)

In [8]:
timeshift

                             name  count
76           Euforija III, ep. 02     18
94                From IV, ep. 01     16
404                        Tvorac      8
75           Euforija III, ep. 01      8
85                          Fokus      8
..                            ...    ...
22              Ben 10 IV, ep. 04      1
21                    Beli očnjak      1
20         Beli lotos III, ep. 06      1
19         Beli lotos III, ep. 01      1
466  Čovek sa gvozdenim pesnicama      1

[478 rows x 2 columns]