In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [11]:
db_uri = "mysql+pymysql://statsuser:statspass@localhost:3306/statsdb"
engine = create_engine(db_uri)

guery = """
SELECT *
FROM statistic
WHERE type = 'mediaSeen_PROGRAM';
"""

In [12]:
df = pd.read_sql(guery, engine)

In [13]:
df.drop_duplicates
df

,id,cusRef,devRef,devType,devModel,timeZone,cusGrRefs,ref,type,name,time,duration,extra,deliveredTS,insertedTS
0,50582124767,185224001684602,1852240016846021,MOTOROLA_4,VIP1113,UTC+01:00,"[""100128"",""100131"",""1006"",""A0"",""C1"",""0"",""A2"",""...",33,mediaSeen_PROGRAM,Kviz 1 na 1,1776722132309,37885,"{""title"":""Kviz 1 na 1"",""genre"":""Zabava"",""start...",1776722394551,2026-04-21 00:00:00
1,50582125023,960152002385458,9601520023854581,MOTOROLA_4,VIP1113,UTC+02:00,"[""100128"",""100131"",""1006"",""C1"",""0"",""V0"",""R1""]",100889,mediaSeen_PROGRAM,Prva,1776722351496,17247,"{""title"":""Na mestu zločina sa Mašanom"",""genre""...",1776722397043,2026-04-21 00:00:00
2,50582125170,964393002402191,9643930024021912,MOTOROLA_4,VIP1113,UTC+02:00,"[""100128"",""100131"",""1006"",""C1"",""0"",""V0"",""R1""]",29,mediaSeen_PROGRAM,Prijatelji,1776722364420,41883,"{""title"":""Prijatelji"",""genre"":""Film"",""startTim...",1776722398517,2026-04-21 00:00:00
3,50582125274,990546002886325,9905460028863251,KREATV_5,VIP4205,UTC+01:00,"[""100128"",""R1"",""1006"",""C1"",""0"",""V0""]",28,mediaSeen_PROGRAM,Divlje pčele,1776722353676,23083,"{""title"":""Divlje pčele"",""genre"":""Film"",""startT...",1776722399558,2026-04-21 00:00:00
4,50582125293,312341002207341,3123410022073411,MOTOROLA_4,VIP1113,UTC+01:00,"[""100128"",""100131"",""1006"",""C1"",""0""]",100865,mediaSeen_PROGRAM,Kad lišće pada,1776722352799,60044,"{""title"":""Kad lišće pada"",""genre"":""Film"",""star...",1776722399732,2026-04-21 00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15076,50595720119,867641001423017,8676410014230171,MOTOROLA_4,VIP1113,UTC+02:00,"[""100128"",""100131"",""1006"",""A0"",""C1"",""0"",""A2"",""...",310,mediaSeen_PROGRAM,Pink,1776808765659,11314,"{""title"":""Ami G Show"",""genre"":""Zabava"",""startT...",1776808780386,2026-04-21 23:59:51
15077,50595720987,121607002470267,1216070024702671,MOTOROLA_4,VIP1113,UTC+01:00,"[""100128"",""100131"",""1006"",""C1"",""0"",""V0"",""R1""]",326,mediaSeen_PROGRAM,Ponos Ratkajevih,1776808555841,20180,"{""title"":""Ponos Ratkajevih"",""genre"":""Film"",""st...",1776808782501,2026-04-21 23:59:54
15078,50595720994,9999783500549999,99997835005499991,AMINO,A139,UTC+02:00,"[""L1"",""L2"",""A0"",""A2""]",29,mediaSeen_PROGRAM,Teorija velikog praska,1776808609686,60034,"{""title"":""Teorija velikog praska"",""genre"":""Fil...",1776808782588,2026-04-21 23:59:54
15079,50595721243,275890001448446,2758900014484462,MOTOROLA_4,VIP1113,UTC+02:00,"[""100131"",""1006"",""A0"",""C1"",""0"",""10010"",""A1"",""A...",29,mediaSeen_PROGRAM,Teški zločini,1776808651086,26023,"{""title"":""Teški zločini"",""genre"":""Film"",""start...",1776808785937,2026-04-21 23:59:54
15080,50595721722,2000000000063067,200000000006306700001,KREATV_5,VIP4205,UTC+02:00,"[""S1"",""100128"",""100131"",""M1"",""M2"",""C1"",""0"",""M0...",403,mediaSeen_PROGRAM,Preživljavanje - Goli i uplašeni,1776808759885,10601,"{""title"":""Preživljavanje - Goli i uplašeni"",""g...",1776808791885,2026-04-21 23:59:54

In [14]:
top_name = (
    df.groupby("name")
    .size()
    .reset_index(name="count")
    .sort_values(by="count", ascending=False)
)

top_name

                                  name  count
210                            Elita 9    664
311   Igra sudbine: Ljubav nakon greha    450
159                       Divlje pčele    424
620                         Pepa prase    380
977                         Zarobljena    354
...                                ...    ...
441                Ljubav na prvi ples      1
442             Ljubav, navika, panika      1
444                      Lopov s krova      1
448            Lovac i ledena kraljica      1
1009               Čitulja za Eskobara      1

[1047 rows x 2 columns]