In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [2]:
db_uri = "mysql+pymysql://statsuser:statspass@localhost:3306/statsdb"
engine = create_engine(db_uri)

guery = """
SELECT *
FROM statistic
WHERE type = 'NETWORK_DvrUsage';
"""

In [3]:
df = pd.read_sql(guery, engine)

In [4]:
df.drop_duplicates()
df

,id,cusRef,devRef,devType,devModel,timeZone,cusGrRefs,ref,type,name,time,duration,extra,deliveredTS,insertedTS
0,50582126070,9999773000789999,99997730007899991,KREATV_5,VIP4205,UTC+02:00,"[""L1"",""L2"",""V0""]",Pink Classic,NETWORK_DvrUsage,Svetlosti pozornice,1776722378551,300021,"{""title"":""Svetlosti pozornice"",""genre"":""Film"",...",1776722404691,2026-04-21 00:00:07
1,50582134556,9999869749519999,99998697495199993,MOTOROLA_4,VIP1113,UTC+02:00,"[""L1"",""L2"",""V0""]",Pink Romance,NETWORK_DvrUsage,Nešto sasvim privatno,1776722420621,240134,"{""title"":""Nešto sasvim privatno"",""genre"":""Film...",1776722441747,2026-04-21 00:00:49
2,50582151572,143097002149196,1430970021491961,MOTOROLA_4,VIP1113,UTC+02:00,"[""100128"",""1006"",""C1"",""0"",""V0"",""R1""]",Happy TV,NETWORK_DvrUsage,Ćirilica,1776722484600,300057,"{""title"":""Ćirilica"",""genre"":""Vijesti"",""startTi...",1776722525925,2026-04-21 00:02:13
3,50582159531,9999552001699999,99995520016999991,MOTOROLA_4,VIP1113,UTC+02:00,"[""L1"",""L2"",""A0""]",Star Channel HD,NETWORK_DvrUsage,Votson,1776722505775,300049,"{""title"":""Votson"",""genre"":""Film"",""startTime"":0...",1776722565397,2026-04-21 00:02:54
4,50582163388,9999630296939999,99996302969399991,AMINO,A139,UTC+02:00,"[""L1"",""L2"",""A0"",""A2""]",National Geographic,NETWORK_DvrUsage,Avionske nesreće,1776722489705,240454,"{""title"":""Avionske nesreće"",""genre"":""Nauka"",""s...",1776722584762,2026-04-21 00:03:13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
841,50595672071,9999552001699999,99995520016999991,MOTOROLA_4,VIP1113,UTC+02:00,"[""L1"",""L2"",""A0""]",Star Channel HD,NETWORK_DvrUsage,Votson,1776808441949,300093,"{""title"":""Votson"",""genre"":""Film"",""startTime"":0...",1776808470989,2026-04-21 23:54:42
842,50595695315,879157001548885,8791570015488851,AMINO,A139,UTC+02:00,"[""100128"",""100130"",""C6"",""1006"",""A0"",""0"",""A2"",""...",Star Crime HD,NETWORK_DvrUsage,Mornarički istražitelji,1776808607567,300403,"{""title"":""Mornarički istražitelji"",""genre"":""Fi...",1776808619995,2026-04-21 23:57:07
843,50595696594,325392002856081,325392002856081241,MOTOROLA_4,VIP1113,UTC+02:00,"[""1006"",""C1"",""0"",""V0"",""R1""]",Pink World Cinema,NETWORK_DvrUsage,Okrutna romansa,1776808598355,300054,"{""title"":""Okrutna romansa"",""genre"":""Film"",""sta...",1776808633480,2026-04-21 23:57:18
844,50595705419,9999416225969999,99994162259699993,MOTOROLA_4,VIP1113,UTC+02:00,"[""L1"",""L2"",""A0"",""A2"",""V0""]",Pink Movies,NETWORK_DvrUsage,Jesen u vinogradu,1776808653641,180066,"{""title"":""Jesen u vinogradu"",""genre"":""Film"",""s...",1776808686923,2026-04-21 23:58:13
845,50595718401,9999552001699999,99995520016999991,MOTOROLA_4,VIP1113,UTC+02:00,"[""L1"",""L2"",""A0""]",Star Channel HD,NETWORK_DvrUsage,Votson,1776808742002,300053,"{""title"":""Votson"",""genre"":""Film"",""startTime"":0...",1776808770997,2026-04-21 23:59:38

In [5]:
import sys
import os

project_root = os.path.abspath(os.path.join(os.getcwd(), "..", ".."))
sys.path.append(project_root)

from processors.network_dvr_usage import process

In [6]:
most_recorded_name = process(df)

most_recorded_name

                                name  total_watch_time
9                            Elita 9          23498511
21           Mornarički istražitelji          20694736
11                   Inspektor Morse          19242902
36    Snajperista - Misija odmetnika          17032704
37               Svetlosti pozornice          14584320
18                    Minecraft Film          13074416
35                       Smrt u raju           8368646
23                         Ne diši 2           7487421
43                       Večera za 5           6540719
10                       Foyleov rat           6388690
0   4TENORA - Nova vokalna šetnja gl           6330208
17                Megalodon 2: Ambis           6316349
50                Čovek po imenu Oto           6013499
28                        Oušnovih 8           5761278
40                            Tragač           5297192
47                   Znaš li tko si?           5144365
44                            Votson           4477511
25                         Noćni let           4362328
24             Nešto sasvim privatno           4140815
39                    Točka okidanja           4061343
16                      Ledena cesta           3732548
1                        Aktuelnosti           3675466
30         Pritajeno zlo: Rakun siti           3540294
7                      Dina prvi deo           3117969
45                        Zamalo raj           3112570
22  Mornarički istražitelji: Nju Orl           2820639
49          Časopis "Pipl" istražuje           2717712
27                          Otvoreno           2593841
14  Krimi petak: Povijesti slučajeva           2469532
31            Prokletstvo ostrva Ouk           2410794
48                          Ćirilica           2160412
29                           Potjera           1960173
41                     Ubilačke igre           1619229
33                        Simpsonovi           1593873
34                         Slagalica           1320337
38                       Teret zveri           1296999
19  Misterija Hane Svensen: Želja za           1140414
26                   Okrutna romansa           1020280
32                            Sestre            910802
5                      Cijena straha            897314
3                   Avionske nesreće            497466
4                              Bahar            427569
2                Auto Market Magazin            420088
42                Ubistvo na kruzeru            197123
6                    Da li ste znali            195922
13                 Jesen u vinogradu            180066
46                Zemlja bez milosti            178345
12                 Isterivači duhova            120031
15  Kung Fu Panda: Praznični specija             58703
8              Dobro jutro, Hrvatska             16742
20                           Mobilni             14372